// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: backend/site/v1/site.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBasicSettingReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 站点ID，可选，如果不传则使用当前站点
	SiteId        int32 `protobuf:"varint,1,opt,name=site_id,json=siteId,proto3" json:"site_id" dc:"站点ID，可选，如果不传则使用当前站点"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBasicSettingReq) Reset() {
	*x = GetBasicSettingReq{}
	mi := &file_backend_site_v1_site_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBasicSettingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasicSettingReq) ProtoMessage() {}

func (x *GetBasicSettingReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_site_v1_site_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasicSettingReq.ProtoReflect.Descriptor instead.
func (*GetBasicSettingReq) Descriptor() ([]byte, []int) {
	return file_backend_site_v1_site_proto_rawDescGZIP(), []int{0}
}

func (x *GetBasicSettingReq) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

type GetBasicSettingRes struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Code                 string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code" dc:"站点代码"`                                                                        // 站点代码
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name" dc:"站点名称"`                                                                        // 站点名称
	RegisterTimeInterval int32                  `protobuf:"varint,3,opt,name=register_time_interval,json=registerTimeInterval,proto3" json:"register_time_interval" dc:"同一IP重复注册时间间隔"` // 同一IP重复注册时间间隔
	SwitchRegister       bool                   `protobuf:"varint,4,opt,name=switch_register,json=switchRegister,proto3" json:"switch_register" dc:"是否开放注册"`                           // 是否开放注册
	IsClose              bool                   `protobuf:"varint,5,opt,name=is_close,json=isClose,proto3" json:"is_close" dc:"是否关闭站点"`                                                // 是否关闭站点
	CloseReason          string                 `protobuf:"bytes,6,opt,name=close_reason,json=closeReason,proto3" json:"close_reason" dc:"关闭原因"`                                       // 关闭原因
	UrlService           string                 `protobuf:"bytes,7,opt,name=url_service,json=urlService,proto3" json:"url_service" dc:"客服链接"`                                          // 客服链接
	UrlAgentPc           string                 `protobuf:"bytes,8,opt,name=url_agent_pc,json=urlAgentPc,proto3" json:"url_agent_pc" dc:"代理链接地址"`                                      // 代理链接地址
	UrlMobile            string                 `protobuf:"bytes,9,opt,name=url_mobile,json=urlMobile,proto3" json:"url_mobile" dc:"手机域名地址"`                                           // 手机域名地址
	UrlAgentRegister     string                 `protobuf:"bytes,10,opt,name=url_agent_register,json=urlAgentRegister,proto3" json:"url_agent_register" dc:"代理推广地址"`                   // 代理推广地址
	MinWithdraw          int32                  `protobuf:"varint,11,opt,name=min_withdraw,json=minWithdraw,proto3" json:"min_withdraw" dc:"单笔最低提现金额"`                                 // 单笔最低提现金额
	MaxWithdraw          int32                  `protobuf:"varint,12,opt,name=max_withdraw,json=maxWithdraw,proto3" json:"max_withdraw" dc:"单笔最高提现金额"`                                 // 单笔最高提现金额
	MobileLogo           string                 `protobuf:"bytes,13,opt,name=mobile_logo,json=mobileLogo,proto3" json:"mobile_logo" dc:"手机端Logo"`                                      // 手机端Logo
	DefaultAgentId       int32                  `protobuf:"varint,14,opt,name=default_agent_id,json=defaultAgentId,proto3" json:"default_agent_id" dc:"默认代理ID"`                        // 默认代理ID
	DefaultAgentName     string                 `protobuf:"bytes,15,opt,name=default_agent_name,json=defaultAgentName,proto3" json:"default_agent_name" dc:"默认代理名称"`                   // 默认代理名称
	Balance              float64                `protobuf:"fixed64,16,opt,name=balance,proto3" json:"balance" dc:"总可用额度"`                                                              // 总可用额度
	BalanceReset         float64                `protobuf:"fixed64,17,opt,name=balance_reset,json=balanceReset,proto3" json:"balance_reset" dc:"剩余额度"`                                 // 剩余额度
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetBasicSettingRes) Reset() {
	*x = GetBasicSettingRes{}
	mi := &file_backend_site_v1_site_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBasicSettingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasicSettingRes) ProtoMessage() {}

func (x *GetBasicSettingRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_site_v1_site_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasicSettingRes.ProtoReflect.Descriptor instead.
func (*GetBasicSettingRes) Descriptor() ([]byte, []int) {
	return file_backend_site_v1_site_proto_rawDescGZIP(), []int{1}
}

func (x *GetBasicSettingRes) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetBasicSettingRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetBasicSettingRes) GetRegisterTimeInterval() int32 {
	if x != nil {
		return x.RegisterTimeInterval
	}
	return 0
}

func (x *GetBasicSettingRes) GetSwitchRegister() bool {
	if x != nil {
		return x.SwitchRegister
	}
	return false
}

func (x *GetBasicSettingRes) GetIsClose() bool {
	if x != nil {
		return x.IsClose
	}
	return false
}

func (x *GetBasicSettingRes) GetCloseReason() string {
	if x != nil {
		return x.CloseReason
	}
	return ""
}

func (x *GetBasicSettingRes) GetUrlService() string {
	if x != nil {
		return x.UrlService
	}
	return ""
}

func (x *GetBasicSettingRes) GetUrlAgentPc() string {
	if x != nil {
		return x.UrlAgentPc
	}
	return ""
}

func (x *GetBasicSettingRes) GetUrlMobile() string {
	if x != nil {
		return x.UrlMobile
	}
	return ""
}

func (x *GetBasicSettingRes) GetUrlAgentRegister() string {
	if x != nil {
		return x.UrlAgentRegister
	}
	return ""
}

func (x *GetBasicSettingRes) GetMinWithdraw() int32 {
	if x != nil {
		return x.MinWithdraw
	}
	return 0
}

func (x *GetBasicSettingRes) GetMaxWithdraw() int32 {
	if x != nil {
		return x.MaxWithdraw
	}
	return 0
}

func (x *GetBasicSettingRes) GetMobileLogo() string {
	if x != nil {
		return x.MobileLogo
	}
	return ""
}

func (x *GetBasicSettingRes) GetDefaultAgentId() int32 {
	if x != nil {
		return x.DefaultAgentId
	}
	return 0
}

func (x *GetBasicSettingRes) GetDefaultAgentName() string {
	if x != nil {
		return x.DefaultAgentName
	}
	return ""
}

func (x *GetBasicSettingRes) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetBasicSettingRes) GetBalanceReset() float64 {
	if x != nil {
		return x.BalanceReset
	}
	return 0
}

type UpdateBasicSettingReq struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SiteId               int32                  `protobuf:"varint,1,opt,name=site_id,json=siteId,proto3" json:"site_id" dc:"站点ID，可选"`                                                  // 站点ID，可选
	RegisterTimeInterval int32                  `protobuf:"varint,2,opt,name=register_time_interval,json=registerTimeInterval,proto3" json:"register_time_interval" dc:"同一IP重复注册时间间隔"` // 同一IP重复注册时间间隔
	SwitchRegister       bool                   `protobuf:"varint,3,opt,name=switch_register,json=switchRegister,proto3" json:"switch_register" dc:"是否开放注册"`                           // 是否开放注册
	IsClose              bool                   `protobuf:"varint,4,opt,name=is_close,json=isClose,proto3" json:"is_close" dc:"是否关闭站点"`                                                // 是否关闭站点
	CloseReason          string                 `protobuf:"bytes,5,opt,name=close_reason,json=closeReason,proto3" json:"close_reason" dc:"关闭原因"`                                       // 关闭原因
	UrlAgentPc           string                 `protobuf:"bytes,6,opt,name=url_agent_pc,json=urlAgentPc,proto3" json:"url_agent_pc" dc:"代理链接地址"`                                      // 代理链接地址
	UrlMobile            string                 `protobuf:"bytes,7,opt,name=url_mobile,json=urlMobile,proto3" json:"url_mobile" dc:"手机域名地址"`                                           // 手机域名地址
	UrlAgentRegister     string                 `protobuf:"bytes,8,opt,name=url_agent_register,json=urlAgentRegister,proto3" json:"url_agent_register" dc:"代理推广地址"`                    // 代理推广地址
	MinWithdraw          int32                  `protobuf:"varint,9,opt,name=min_withdraw,json=minWithdraw,proto3" json:"min_withdraw" dc:"单笔最低提现金额"`                                  // 单笔最低提现金额
	MaxWithdraw          int32                  `protobuf:"varint,10,opt,name=max_withdraw,json=maxWithdraw,proto3" json:"max_withdraw" dc:"单笔最高提现金额"`                                 // 单笔最高提现金额
	MobileLogo           string                 `protobuf:"bytes,11,opt,name=mobile_logo,json=mobileLogo,proto3" json:"mobile_logo" dc:"手机端Logo"`                                      // 手机端Logo
	UrlService           string                 `protobuf:"bytes,12,opt,name=url_service,json=urlService,proto3" json:"url_service" dc:"客服链接"`                                         // 客服链接
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateBasicSettingReq) Reset() {
	*x = UpdateBasicSettingReq{}
	mi := &file_backend_site_v1_site_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBasicSettingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBasicSettingReq) ProtoMessage() {}

func (x *UpdateBasicSettingReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_site_v1_site_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBasicSettingReq.ProtoReflect.Descriptor instead.
func (*UpdateBasicSettingReq) Descriptor() ([]byte, []int) {
	return file_backend_site_v1_site_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateBasicSettingReq) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *UpdateBasicSettingReq) GetRegisterTimeInterval() int32 {
	if x != nil {
		return x.RegisterTimeInterval
	}
	return 0
}

func (x *UpdateBasicSettingReq) GetSwitchRegister() bool {
	if x != nil {
		return x.SwitchRegister
	}
	return false
}

func (x *UpdateBasicSettingReq) GetIsClose() bool {
	if x != nil {
		return x.IsClose
	}
	return false
}

func (x *UpdateBasicSettingReq) GetCloseReason() string {
	if x != nil {
		return x.CloseReason
	}
	return ""
}

func (x *UpdateBasicSettingReq) GetUrlAgentPc() string {
	if x != nil {
		return x.UrlAgentPc
	}
	return ""
}

func (x *UpdateBasicSettingReq) GetUrlMobile() string {
	if x != nil {
		return x.UrlMobile
	}
	return ""
}

func (x *UpdateBasicSettingReq) GetUrlAgentRegister() string {
	if x != nil {
		return x.UrlAgentRegister
	}
	return ""
}

func (x *UpdateBasicSettingReq) GetMinWithdraw() int32 {
	if x != nil {
		return x.MinWithdraw
	}
	return 0
}

func (x *UpdateBasicSettingReq) GetMaxWithdraw() int32 {
	if x != nil {
		return x.MaxWithdraw
	}
	return 0
}

func (x *UpdateBasicSettingReq) GetMobileLogo() string {
	if x != nil {
		return x.MobileLogo
	}
	return ""
}

func (x *UpdateBasicSettingReq) GetUrlService() string {
	if x != nil {
		return x.UrlService
	}
	return ""
}

type UpdateBasicSettingRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message" dc:"响应消息"` // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBasicSettingRes) Reset() {
	*x = UpdateBasicSettingRes{}
	mi := &file_backend_site_v1_site_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBasicSettingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBasicSettingRes) ProtoMessage() {}

func (x *UpdateBasicSettingRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_site_v1_site_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBasicSettingRes.ProtoReflect.Descriptor instead.
func (*UpdateBasicSettingRes) Descriptor() ([]byte, []int) {
	return file_backend_site_v1_site_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateBasicSettingRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_backend_site_v1_site_proto protoreflect.FileDescriptor

const file_backend_site_v1_site_proto_rawDesc = "" +
	"\n" +
	"\x1abackend/site/v1/site.proto\x12\x04site\"-\n" +
	"\x12GetBasicSettingReq\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\x05R\x06siteId\"\xe7\x04\n" +
	"\x12GetBasicSettingRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x124\n" +
	"\x16register_time_interval\x18\x03 \x01(\x05R\x14registerTimeInterval\x12'\n" +
	"\x0fswitch_register\x18\x04 \x01(\bR\x0eswitchRegister\x12\x19\n" +
	"\bis_close\x18\x05 \x01(\bR\aisClose\x12!\n" +
	"\fclose_reason\x18\x06 \x01(\tR\vcloseReason\x12\x1f\n" +
	"\vurl_service\x18\a \x01(\tR\n" +
	"urlService\x12 \n" +
	"\furl_agent_pc\x18\b \x01(\tR\n" +
	"urlAgentPc\x12\x1d\n" +
	"\n" +
	"url_mobile\x18\t \x01(\tR\turlMobile\x12,\n" +
	"\x12url_agent_register\x18\n" +
	" \x01(\tR\x10urlAgentRegister\x12!\n" +
	"\fmin_withdraw\x18\v \x01(\x05R\vminWithdraw\x12!\n" +
	"\fmax_withdraw\x18\f \x01(\x05R\vmaxWithdraw\x12\x1f\n" +
	"\vmobile_logo\x18\r \x01(\tR\n" +
	"mobileLogo\x12(\n" +
	"\x10default_agent_id\x18\x0e \x01(\x05R\x0edefaultAgentId\x12,\n" +
	"\x12default_agent_name\x18\x0f \x01(\tR\x10defaultAgentName\x12\x18\n" +
	"\abalance\x18\x10 \x01(\x01R\abalance\x12#\n" +
	"\rbalance_reset\x18\x11 \x01(\x01R\fbalanceReset\"\xc4\x03\n" +
	"\x15UpdateBasicSettingReq\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\x05R\x06siteId\x124\n" +
	"\x16register_time_interval\x18\x02 \x01(\x05R\x14registerTimeInterval\x12'\n" +
	"\x0fswitch_register\x18\x03 \x01(\bR\x0eswitchRegister\x12\x19\n" +
	"\bis_close\x18\x04 \x01(\bR\aisClose\x12!\n" +
	"\fclose_reason\x18\x05 \x01(\tR\vcloseReason\x12 \n" +
	"\furl_agent_pc\x18\x06 \x01(\tR\n" +
	"urlAgentPc\x12\x1d\n" +
	"\n" +
	"url_mobile\x18\a \x01(\tR\turlMobile\x12,\n" +
	"\x12url_agent_register\x18\b \x01(\tR\x10urlAgentRegister\x12!\n" +
	"\fmin_withdraw\x18\t \x01(\x05R\vminWithdraw\x12!\n" +
	"\fmax_withdraw\x18\n" +
	" \x01(\x05R\vmaxWithdraw\x12\x1f\n" +
	"\vmobile_logo\x18\v \x01(\tR\n" +
	"mobileLogo\x12\x1f\n" +
	"\vurl_service\x18\f \x01(\tR\n" +
	"urlService\"1\n" +
	"\x15UpdateBasicSettingRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa1\x01\n" +
	"\x04Site\x12G\n" +
	"\x0fGetBasicSetting\x12\x18.site.GetBasicSettingReq\x1a\x18.site.GetBasicSettingRes\"\x00\x12P\n" +
	"\x12UpdateBasicSetting\x12\x1b.site.UpdateBasicSettingReq\x1a\x1b.site.UpdateBasicSettingRes\"\x00B&Z$jh_admin_service/api/backend/site/v1b\x06proto3"

var (
	file_backend_site_v1_site_proto_rawDescOnce sync.Once
	file_backend_site_v1_site_proto_rawDescData []byte
)

func file_backend_site_v1_site_proto_rawDescGZIP() []byte {
	file_backend_site_v1_site_proto_rawDescOnce.Do(func() {
		file_backend_site_v1_site_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_site_v1_site_proto_rawDesc), len(file_backend_site_v1_site_proto_rawDesc)))
	})
	return file_backend_site_v1_site_proto_rawDescData
}

var file_backend_site_v1_site_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_backend_site_v1_site_proto_goTypes = []any{
	(*GetBasicSettingReq)(nil),    // 0: site.GetBasicSettingReq
	(*GetBasicSettingRes)(nil),    // 1: site.GetBasicSettingRes
	(*UpdateBasicSettingReq)(nil), // 2: site.UpdateBasicSettingReq
	(*UpdateBasicSettingRes)(nil), // 3: site.UpdateBasicSettingRes
}
var file_backend_site_v1_site_proto_depIdxs = []int32{
	0, // 0: site.Site.GetBasicSetting:input_type -> site.GetBasicSettingReq
	2, // 1: site.Site.UpdateBasicSetting:input_type -> site.UpdateBasicSettingReq
	1, // 2: site.Site.GetBasicSetting:output_type -> site.GetBasicSettingRes
	3, // 3: site.Site.UpdateBasicSetting:output_type -> site.UpdateBasicSettingRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_backend_site_v1_site_proto_init() }
func file_backend_site_v1_site_proto_init() {
	if File_backend_site_v1_site_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_site_v1_site_proto_rawDesc), len(file_backend_site_v1_site_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_site_v1_site_proto_goTypes,
		DependencyIndexes: file_backend_site_v1_site_proto_depIdxs,
		MessageInfos:      file_backend_site_v1_site_proto_msgTypes,
	}.Build()
	File_backend_site_v1_site_proto = out.File
	file_backend_site_v1_site_proto_goTypes = nil
	file_backend_site_v1_site_proto_depIdxs = nil
}
