// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: site/v1/site.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Site_GetBasicSetting_FullMethodName    = "/site.Site/GetBasicSetting"
	Site_UpdateBasicSetting_FullMethodName = "/site.Site/UpdateBasicSetting"
)

// SiteClient is the client API for Site service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SiteClient interface {
	GetBasicSetting(ctx context.Context, in *GetBasicSettingReq, opts ...grpc.CallOption) (*GetBasicSettingRes, error)
	UpdateBasicSetting(ctx context.Context, in *UpdateBasicSettingReq, opts ...grpc.CallOption) (*UpdateBasicSettingRes, error)
}

type siteClient struct {
	cc grpc.ClientConnInterface
}

func NewSiteClient(cc grpc.ClientConnInterface) SiteClient {
	return &siteClient{cc}
}

func (c *siteClient) GetBasicSetting(ctx context.Context, in *GetBasicSettingReq, opts ...grpc.CallOption) (*GetBasicSettingRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBasicSettingRes)
	err := c.cc.Invoke(ctx, Site_GetBasicSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *siteClient) UpdateBasicSetting(ctx context.Context, in *UpdateBasicSettingReq, opts ...grpc.CallOption) (*UpdateBasicSettingRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBasicSettingRes)
	err := c.cc.Invoke(ctx, Site_UpdateBasicSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SiteServer is the server API for Site service.
// All implementations must embed UnimplementedSiteServer
// for forward compatibility.
type SiteServer interface {
	GetBasicSetting(context.Context, *GetBasicSettingReq) (*GetBasicSettingRes, error)
	UpdateBasicSetting(context.Context, *UpdateBasicSettingReq) (*UpdateBasicSettingRes, error)
	mustEmbedUnimplementedSiteServer()
}

// UnimplementedSiteServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSiteServer struct{}

func (UnimplementedSiteServer) GetBasicSetting(context.Context, *GetBasicSettingReq) (*GetBasicSettingRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBasicSetting not implemented")
}
func (UnimplementedSiteServer) UpdateBasicSetting(context.Context, *UpdateBasicSettingReq) (*UpdateBasicSettingRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBasicSetting not implemented")
}
func (UnimplementedSiteServer) mustEmbedUnimplementedSiteServer() {}
func (UnimplementedSiteServer) testEmbeddedByValue()              {}

// UnsafeSiteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SiteServer will
// result in compilation errors.
type UnsafeSiteServer interface {
	mustEmbedUnimplementedSiteServer()
}

func RegisterSiteServer(s grpc.ServiceRegistrar, srv SiteServer) {
	// If the following call panics, it indicates UnimplementedSiteServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Site_ServiceDesc, srv)
}

func _Site_GetBasicSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBasicSettingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServer).GetBasicSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Site_GetBasicSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServer).GetBasicSetting(ctx, req.(*GetBasicSettingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Site_UpdateBasicSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBasicSettingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServer).UpdateBasicSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Site_UpdateBasicSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServer).UpdateBasicSetting(ctx, req.(*UpdateBasicSettingReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Site_ServiceDesc is the grpc.ServiceDesc for Site service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Site_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "site.Site",
	HandlerType: (*SiteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBasicSetting",
			Handler:    _Site_GetBasicSetting_Handler,
		},
		{
			MethodName: "UpdateBasicSetting",
			Handler:    _Site_UpdateBasicSetting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "site/v1/site.proto",
}
