// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: site/v1/site.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBasicSettingReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 站点ID，可选，如果不传则使用当前站点
	SiteId        int32 `protobuf:"varint,1,opt,name=SiteId,proto3" json:"SiteId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBasicSettingReq) Reset() {
	*x = GetBasicSettingReq{}
	mi := &file_site_v1_site_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBasicSettingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasicSettingReq) ProtoMessage() {}

func (x *GetBasicSettingReq) ProtoReflect() protoreflect.Message {
	mi := &file_site_v1_site_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasicSettingReq.ProtoReflect.Descriptor instead.
func (*GetBasicSettingReq) Descriptor() ([]byte, []int) {
	return file_site_v1_site_proto_rawDescGZIP(), []int{0}
}

func (x *GetBasicSettingReq) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

type GetBasicSettingRes struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Code                 string                 `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`                                  // 站点代码
	Name                 string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`                                  // 站点名称
	RegisterTimeInterval int32                  `protobuf:"varint,3,opt,name=RegisterTimeInterval,proto3" json:"RegisterTimeInterval,omitempty"` // 同一IP重复注册时间间隔
	SwitchRegister       bool                   `protobuf:"varint,4,opt,name=SwitchRegister,proto3" json:"SwitchRegister,omitempty"`             // 是否开放注册
	IsClose              bool                   `protobuf:"varint,5,opt,name=IsClose,proto3" json:"IsClose,omitempty"`                           // 是否关闭站点
	CloseReason          string                 `protobuf:"bytes,6,opt,name=CloseReason,proto3" json:"CloseReason,omitempty"`                    // 关闭原因
	ServiceUrl           string                 `protobuf:"bytes,7,opt,name=ServiceUrl,proto3" json:"ServiceUrl,omitempty"`                      // 客服链接
	AgentUrl             string                 `protobuf:"bytes,8,opt,name=AgentUrl,proto3" json:"AgentUrl,omitempty"`                          // 代理链接地址
	MobileUrl            string                 `protobuf:"bytes,9,opt,name=MobileUrl,proto3" json:"MobileUrl,omitempty"`                        // 手机域名地址
	AgentRegisterUrl     string                 `protobuf:"bytes,10,opt,name=AgentRegisterUrl,proto3" json:"AgentRegisterUrl,omitempty"`         // 代理推广地址
	MinWithdraw          float64                `protobuf:"fixed64,11,opt,name=MinWithdraw,proto3" json:"MinWithdraw,omitempty"`                 // 单笔最低提现金额
	MaxWithdraw          float64                `protobuf:"fixed64,12,opt,name=MaxWithdraw,proto3" json:"MaxWithdraw,omitempty"`                 // 单笔最高提现金额
	MobileLogo           string                 `protobuf:"bytes,13,opt,name=MobileLogo,proto3" json:"MobileLogo,omitempty"`                     // 手机端Logo
	DefaultAgentId       int32                  `protobuf:"varint,14,opt,name=DefaultAgentId,proto3" json:"DefaultAgentId,omitempty"`            // 默认代理ID
	DefaultAgentName     string                 `protobuf:"bytes,15,opt,name=DefaultAgentName,proto3" json:"DefaultAgentName,omitempty"`         // 默认代理名称
	Balance              float64                `protobuf:"fixed64,16,opt,name=Balance,proto3" json:"Balance,omitempty"`                         // 总可用额度
	BalanceReset         float64                `protobuf:"fixed64,17,opt,name=BalanceReset,proto3" json:"BalanceReset,omitempty"`               // 剩余额度
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetBasicSettingRes) Reset() {
	*x = GetBasicSettingRes{}
	mi := &file_site_v1_site_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBasicSettingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasicSettingRes) ProtoMessage() {}

func (x *GetBasicSettingRes) ProtoReflect() protoreflect.Message {
	mi := &file_site_v1_site_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasicSettingRes.ProtoReflect.Descriptor instead.
func (*GetBasicSettingRes) Descriptor() ([]byte, []int) {
	return file_site_v1_site_proto_rawDescGZIP(), []int{1}
}

func (x *GetBasicSettingRes) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetBasicSettingRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetBasicSettingRes) GetRegisterTimeInterval() int32 {
	if x != nil {
		return x.RegisterTimeInterval
	}
	return 0
}

func (x *GetBasicSettingRes) GetSwitchRegister() bool {
	if x != nil {
		return x.SwitchRegister
	}
	return false
}

func (x *GetBasicSettingRes) GetIsClose() bool {
	if x != nil {
		return x.IsClose
	}
	return false
}

func (x *GetBasicSettingRes) GetCloseReason() string {
	if x != nil {
		return x.CloseReason
	}
	return ""
}

func (x *GetBasicSettingRes) GetServiceUrl() string {
	if x != nil {
		return x.ServiceUrl
	}
	return ""
}

func (x *GetBasicSettingRes) GetAgentUrl() string {
	if x != nil {
		return x.AgentUrl
	}
	return ""
}

func (x *GetBasicSettingRes) GetMobileUrl() string {
	if x != nil {
		return x.MobileUrl
	}
	return ""
}

func (x *GetBasicSettingRes) GetAgentRegisterUrl() string {
	if x != nil {
		return x.AgentRegisterUrl
	}
	return ""
}

func (x *GetBasicSettingRes) GetMinWithdraw() float64 {
	if x != nil {
		return x.MinWithdraw
	}
	return 0
}

func (x *GetBasicSettingRes) GetMaxWithdraw() float64 {
	if x != nil {
		return x.MaxWithdraw
	}
	return 0
}

func (x *GetBasicSettingRes) GetMobileLogo() string {
	if x != nil {
		return x.MobileLogo
	}
	return ""
}

func (x *GetBasicSettingRes) GetDefaultAgentId() int32 {
	if x != nil {
		return x.DefaultAgentId
	}
	return 0
}

func (x *GetBasicSettingRes) GetDefaultAgentName() string {
	if x != nil {
		return x.DefaultAgentName
	}
	return ""
}

func (x *GetBasicSettingRes) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetBasicSettingRes) GetBalanceReset() float64 {
	if x != nil {
		return x.BalanceReset
	}
	return 0
}

type UpdateBasicSettingReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SiteId           int32                  `protobuf:"varint,1,opt,name=SiteId,proto3" json:"SiteId,omitempty"`                    // 站点ID，可选
	IpRegisterTime   int32                  `protobuf:"varint,2,opt,name=IpRegisterTime,proto3" json:"IpRegisterTime,omitempty"`    // 同一IP重复注册时间间隔
	OpenRegister     bool                   `protobuf:"varint,3,opt,name=OpenRegister,proto3" json:"OpenRegister,omitempty"`        // 是否开放注册
	Close            bool                   `protobuf:"varint,4,opt,name=Close,proto3" json:"Close,omitempty"`                      // 是否关闭站点
	CloseReason      string                 `protobuf:"bytes,5,opt,name=CloseReason,proto3" json:"CloseReason,omitempty"`           // 关闭原因
	AgentUrl         string                 `protobuf:"bytes,6,opt,name=AgentUrl,proto3" json:"AgentUrl,omitempty"`                 // 代理链接地址
	MobileUrl        string                 `protobuf:"bytes,7,opt,name=MobileUrl,proto3" json:"MobileUrl,omitempty"`               // 手机域名地址
	AgentRegisterUrl string                 `protobuf:"bytes,8,opt,name=AgentRegisterUrl,proto3" json:"AgentRegisterUrl,omitempty"` // 代理推广地址
	MinWithdraw      float64                `protobuf:"fixed64,9,opt,name=MinWithdraw,proto3" json:"MinWithdraw,omitempty"`         // 单笔最低提现金额
	MaxWithdraw      float64                `protobuf:"fixed64,10,opt,name=MaxWithdraw,proto3" json:"MaxWithdraw,omitempty"`        // 单笔最高提现金额
	MobileLogo       string                 `protobuf:"bytes,11,opt,name=MobileLogo,proto3" json:"MobileLogo,omitempty"`            // 手机端Logo
	ServiceUrl       string                 `protobuf:"bytes,12,opt,name=ServiceUrl,proto3" json:"ServiceUrl,omitempty"`            // 客服链接
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateBasicSettingReq) Reset() {
	*x = UpdateBasicSettingReq{}
	mi := &file_site_v1_site_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBasicSettingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBasicSettingReq) ProtoMessage() {}

func (x *UpdateBasicSettingReq) ProtoReflect() protoreflect.Message {
	mi := &file_site_v1_site_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBasicSettingReq.ProtoReflect.Descriptor instead.
func (*UpdateBasicSettingReq) Descriptor() ([]byte, []int) {
	return file_site_v1_site_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateBasicSettingReq) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *UpdateBasicSettingReq) GetIpRegisterTime() int32 {
	if x != nil {
		return x.IpRegisterTime
	}
	return 0
}

func (x *UpdateBasicSettingReq) GetOpenRegister() bool {
	if x != nil {
		return x.OpenRegister
	}
	return false
}

func (x *UpdateBasicSettingReq) GetClose() bool {
	if x != nil {
		return x.Close
	}
	return false
}

func (x *UpdateBasicSettingReq) GetCloseReason() string {
	if x != nil {
		return x.CloseReason
	}
	return ""
}

func (x *UpdateBasicSettingReq) GetAgentUrl() string {
	if x != nil {
		return x.AgentUrl
	}
	return ""
}

func (x *UpdateBasicSettingReq) GetMobileUrl() string {
	if x != nil {
		return x.MobileUrl
	}
	return ""
}

func (x *UpdateBasicSettingReq) GetAgentRegisterUrl() string {
	if x != nil {
		return x.AgentRegisterUrl
	}
	return ""
}

func (x *UpdateBasicSettingReq) GetMinWithdraw() float64 {
	if x != nil {
		return x.MinWithdraw
	}
	return 0
}

func (x *UpdateBasicSettingReq) GetMaxWithdraw() float64 {
	if x != nil {
		return x.MaxWithdraw
	}
	return 0
}

func (x *UpdateBasicSettingReq) GetMobileLogo() string {
	if x != nil {
		return x.MobileLogo
	}
	return ""
}

func (x *UpdateBasicSettingReq) GetServiceUrl() string {
	if x != nil {
		return x.ServiceUrl
	}
	return ""
}

type UpdateBasicSettingRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"` // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBasicSettingRes) Reset() {
	*x = UpdateBasicSettingRes{}
	mi := &file_site_v1_site_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBasicSettingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBasicSettingRes) ProtoMessage() {}

func (x *UpdateBasicSettingRes) ProtoReflect() protoreflect.Message {
	mi := &file_site_v1_site_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBasicSettingRes.ProtoReflect.Descriptor instead.
func (*UpdateBasicSettingRes) Descriptor() ([]byte, []int) {
	return file_site_v1_site_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateBasicSettingRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_site_v1_site_proto protoreflect.FileDescriptor

const file_site_v1_site_proto_rawDesc = "" +
	"\n" +
	"\x12site/v1/site.proto\x12\x04site\",\n" +
	"\x12GetBasicSettingReq\x12\x16\n" +
	"\x06SiteId\x18\x01 \x01(\x05R\x06SiteId\"\xd0\x04\n" +
	"\x12GetBasicSettingRes\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\tR\x04Code\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x122\n" +
	"\x14RegisterTimeInterval\x18\x03 \x01(\x05R\x14RegisterTimeInterval\x12&\n" +
	"\x0eSwitchRegister\x18\x04 \x01(\bR\x0eSwitchRegister\x12\x18\n" +
	"\aIsClose\x18\x05 \x01(\bR\aIsClose\x12 \n" +
	"\vCloseReason\x18\x06 \x01(\tR\vCloseReason\x12\x1e\n" +
	"\n" +
	"ServiceUrl\x18\a \x01(\tR\n" +
	"ServiceUrl\x12\x1a\n" +
	"\bAgentUrl\x18\b \x01(\tR\bAgentUrl\x12\x1c\n" +
	"\tMobileUrl\x18\t \x01(\tR\tMobileUrl\x12*\n" +
	"\x10AgentRegisterUrl\x18\n" +
	" \x01(\tR\x10AgentRegisterUrl\x12 \n" +
	"\vMinWithdraw\x18\v \x01(\x01R\vMinWithdraw\x12 \n" +
	"\vMaxWithdraw\x18\f \x01(\x01R\vMaxWithdraw\x12\x1e\n" +
	"\n" +
	"MobileLogo\x18\r \x01(\tR\n" +
	"MobileLogo\x12&\n" +
	"\x0eDefaultAgentId\x18\x0e \x01(\x05R\x0eDefaultAgentId\x12*\n" +
	"\x10DefaultAgentName\x18\x0f \x01(\tR\x10DefaultAgentName\x12\x18\n" +
	"\aBalance\x18\x10 \x01(\x01R\aBalance\x12\"\n" +
	"\fBalanceReset\x18\x11 \x01(\x01R\fBalanceReset\"\x9d\x03\n" +
	"\x15UpdateBasicSettingReq\x12\x16\n" +
	"\x06SiteId\x18\x01 \x01(\x05R\x06SiteId\x12&\n" +
	"\x0eIpRegisterTime\x18\x02 \x01(\x05R\x0eIpRegisterTime\x12\"\n" +
	"\fOpenRegister\x18\x03 \x01(\bR\fOpenRegister\x12\x14\n" +
	"\x05Close\x18\x04 \x01(\bR\x05Close\x12 \n" +
	"\vCloseReason\x18\x05 \x01(\tR\vCloseReason\x12\x1a\n" +
	"\bAgentUrl\x18\x06 \x01(\tR\bAgentUrl\x12\x1c\n" +
	"\tMobileUrl\x18\a \x01(\tR\tMobileUrl\x12*\n" +
	"\x10AgentRegisterUrl\x18\b \x01(\tR\x10AgentRegisterUrl\x12 \n" +
	"\vMinWithdraw\x18\t \x01(\x01R\vMinWithdraw\x12 \n" +
	"\vMaxWithdraw\x18\n" +
	" \x01(\x01R\vMaxWithdraw\x12\x1e\n" +
	"\n" +
	"MobileLogo\x18\v \x01(\tR\n" +
	"MobileLogo\x12\x1e\n" +
	"\n" +
	"ServiceUrl\x18\f \x01(\tR\n" +
	"ServiceUrl\"1\n" +
	"\x15UpdateBasicSettingRes\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage2\xa1\x01\n" +
	"\x04Site\x12G\n" +
	"\x0fGetBasicSetting\x12\x18.site.GetBasicSettingReq\x1a\x18.site.GetBasicSettingRes\"\x00\x12P\n" +
	"\x12UpdateBasicSetting\x12\x1b.site.UpdateBasicSettingReq\x1a\x1b.site.UpdateBasicSettingRes\"\x00B\x1dZ\x1bjh_user_service/api/site/v1b\x06proto3"

var (
	file_site_v1_site_proto_rawDescOnce sync.Once
	file_site_v1_site_proto_rawDescData []byte
)

func file_site_v1_site_proto_rawDescGZIP() []byte {
	file_site_v1_site_proto_rawDescOnce.Do(func() {
		file_site_v1_site_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_site_v1_site_proto_rawDesc), len(file_site_v1_site_proto_rawDesc)))
	})
	return file_site_v1_site_proto_rawDescData
}

var file_site_v1_site_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_site_v1_site_proto_goTypes = []any{
	(*GetBasicSettingReq)(nil),    // 0: site.GetBasicSettingReq
	(*GetBasicSettingRes)(nil),    // 1: site.GetBasicSettingRes
	(*UpdateBasicSettingReq)(nil), // 2: site.UpdateBasicSettingReq
	(*UpdateBasicSettingRes)(nil), // 3: site.UpdateBasicSettingRes
}
var file_site_v1_site_proto_depIdxs = []int32{
	0, // 0: site.Site.GetBasicSetting:input_type -> site.GetBasicSettingReq
	2, // 1: site.Site.UpdateBasicSetting:input_type -> site.UpdateBasicSettingReq
	1, // 2: site.Site.GetBasicSetting:output_type -> site.GetBasicSettingRes
	3, // 3: site.Site.UpdateBasicSetting:output_type -> site.UpdateBasicSettingRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_site_v1_site_proto_init() }
func file_site_v1_site_proto_init() {
	if File_site_v1_site_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_site_v1_site_proto_rawDesc), len(file_site_v1_site_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_site_v1_site_proto_goTypes,
		DependencyIndexes: file_site_v1_site_proto_depIdxs,
		MessageInfos:      file_site_v1_site_proto_msgTypes,
	}.Build()
	File_site_v1_site_proto = out.File
	file_site_v1_site_proto_goTypes = nil
	file_site_v1_site_proto_depIdxs = nil
}
