// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: backend/role/v1/role.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRoleListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        int32                  `protobuf:"varint,1,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty" dc:"站点ID"` // 站点ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleListReq) Reset() {
	*x = GetRoleListReq{}
	mi := &file_backend_role_v1_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleListReq) ProtoMessage() {}

func (x *GetRoleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_role_v1_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleListReq.ProtoReflect.Descriptor instead.
func (*GetRoleListReq) Descriptor() ([]byte, []int) {
	return file_backend_role_v1_role_proto_rawDescGZIP(), []int{0}
}

func (x *GetRoleListReq) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

type RoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"角色ID"`                                 // 角色ID
	SiteId        int32                  `protobuf:"varint,2,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty" dc:"站点ID"`           // 站点ID
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty" dc:"角色名称"`                              // 角色名称
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty" dc:"状态：0=禁用，1=启用"`                 // 状态：0=禁用，1=启用
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" dc:"创建时间戳"` // 创建时间戳
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" dc:"更新时间戳"` // 更新时间戳
	Permissions   string                 `protobuf:"bytes,7,opt,name=permissions,proto3" json:"permissions,omitempty" dc:"权限配置"`                // 权限配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_backend_role_v1_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_role_v1_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_backend_role_v1_role_proto_rawDescGZIP(), []int{1}
}

func (x *RoleInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleInfo) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *RoleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RoleInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RoleInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *RoleInfo) GetPermissions() string {
	if x != nil {
		return x.Permissions
	}
	return ""
}

type GetRoleListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*RoleInfo            `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty" dc:"角色列表"` // 角色列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleListRes) Reset() {
	*x = GetRoleListRes{}
	mi := &file_backend_role_v1_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleListRes) ProtoMessage() {}

func (x *GetRoleListRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_role_v1_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleListRes.ProtoReflect.Descriptor instead.
func (*GetRoleListRes) Descriptor() ([]byte, []int) {
	return file_backend_role_v1_role_proto_rawDescGZIP(), []int{2}
}

func (x *GetRoleListRes) GetRoles() []*RoleInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_backend_role_v1_role_proto protoreflect.FileDescriptor

const file_backend_role_v1_role_proto_rawDesc = "" +
	"\n" +
	"\x1abackend/role/v1/role.proto\x12\x04role\")\n" +
	"\x0eGetRoleListReq\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\x05R\x06siteId\"\xbf\x01\n" +
	"\bRoleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\asite_id\x18\x02 \x01(\x05R\x06siteId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\x12 \n" +
	"\vpermissions\x18\a \x01(\tR\vpermissions\"6\n" +
	"\x0eGetRoleListRes\x12$\n" +
	"\x05roles\x18\x01 \x03(\v2\x0e.role.RoleInfoR\x05roles2C\n" +
	"\x04Role\x12;\n" +
	"\vGetRoleList\x12\x14.role.GetRoleListReq\x1a\x14.role.GetRoleListRes\"\x00B&Z$jh_admin_service/api/backend/role/v1b\x06proto3"

var (
	file_backend_role_v1_role_proto_rawDescOnce sync.Once
	file_backend_role_v1_role_proto_rawDescData []byte
)

func file_backend_role_v1_role_proto_rawDescGZIP() []byte {
	file_backend_role_v1_role_proto_rawDescOnce.Do(func() {
		file_backend_role_v1_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_role_v1_role_proto_rawDesc), len(file_backend_role_v1_role_proto_rawDesc)))
	})
	return file_backend_role_v1_role_proto_rawDescData
}

var file_backend_role_v1_role_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_backend_role_v1_role_proto_goTypes = []any{
	(*GetRoleListReq)(nil), // 0: role.GetRoleListReq
	(*RoleInfo)(nil),       // 1: role.RoleInfo
	(*GetRoleListRes)(nil), // 2: role.GetRoleListRes
}
var file_backend_role_v1_role_proto_depIdxs = []int32{
	1, // 0: role.GetRoleListRes.roles:type_name -> role.RoleInfo
	0, // 1: role.Role.GetRoleList:input_type -> role.GetRoleListReq
	2, // 2: role.Role.GetRoleList:output_type -> role.GetRoleListRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_backend_role_v1_role_proto_init() }
func file_backend_role_v1_role_proto_init() {
	if File_backend_role_v1_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_role_v1_role_proto_rawDesc), len(file_backend_role_v1_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_role_v1_role_proto_goTypes,
		DependencyIndexes: file_backend_role_v1_role_proto_depIdxs,
		MessageInfos:      file_backend_role_v1_role_proto_msgTypes,
	}.Build()
	File_backend_role_v1_role_proto = out.File
	file_backend_role_v1_role_proto_goTypes = nil
	file_backend_role_v1_role_proto_depIdxs = nil
}
