// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: backend/role/v1/role.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRoleListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        int32                  `protobuf:"varint,1,opt,name=site_id,json=siteId,proto3" json:"site_id" dc:"站点ID"` // 站点ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleListReq) Reset() {
	*x = GetRoleListReq{}
	mi := &file_backend_role_v1_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleListReq) ProtoMessage() {}

func (x *GetRoleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_role_v1_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleListReq.ProtoReflect.Descriptor instead.
func (*GetRoleListReq) Descriptor() ([]byte, []int) {
	return file_backend_role_v1_role_proto_rawDescGZIP(), []int{0}
}

func (x *GetRoleListReq) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

type RoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" dc:"角色ID"`                                 // 角色ID
	SiteId        int32                  `protobuf:"varint,2,opt,name=site_id,json=siteId,proto3" json:"site_id" dc:"站点ID"`           // 站点ID
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name" dc:"角色名称"`                              // 角色名称
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status" dc:"状态：0=禁用，1=启用"`                 // 状态：0=禁用，1=启用
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at" dc:"创建时间戳"` // 创建时间戳
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at" dc:"更新时间戳"` // 更新时间戳
	Permissions   string                 `protobuf:"bytes,7,opt,name=permissions,proto3" json:"permissions" dc:"权限配置"`                // 权限配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_backend_role_v1_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_role_v1_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_backend_role_v1_role_proto_rawDescGZIP(), []int{1}
}

func (x *RoleInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleInfo) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *RoleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RoleInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RoleInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *RoleInfo) GetPermissions() string {
	if x != nil {
		return x.Permissions
	}
	return ""
}

type GetRoleListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*RoleInfo            `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles" dc:"角色列表"` // 角色列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleListRes) Reset() {
	*x = GetRoleListRes{}
	mi := &file_backend_role_v1_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleListRes) ProtoMessage() {}

func (x *GetRoleListRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_role_v1_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleListRes.ProtoReflect.Descriptor instead.
func (*GetRoleListRes) Descriptor() ([]byte, []int) {
	return file_backend_role_v1_role_proto_rawDescGZIP(), []int{2}
}

func (x *GetRoleListRes) GetRoles() []*RoleInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

// 创建角色请求
type CreateRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        int32                  `protobuf:"varint,1,opt,name=site_id,json=siteId,proto3" json:"site_id" dc:"站点ID"` // 站点ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name" dc:"角色名称"`                    // 角色名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleReq) Reset() {
	*x = CreateRoleReq{}
	mi := &file_backend_role_v1_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleReq) ProtoMessage() {}

func (x *CreateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_role_v1_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleReq.ProtoReflect.Descriptor instead.
func (*CreateRoleReq) Descriptor() ([]byte, []int) {
	return file_backend_role_v1_role_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoleReq) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *CreateRoleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 创建角色响应
type CreateRoleRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success" dc:"是否成功"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message" dc:"响应消息"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRes) Reset() {
	*x = CreateRoleRes{}
	mi := &file_backend_role_v1_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRes) ProtoMessage() {}

func (x *CreateRoleRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_role_v1_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRes.ProtoReflect.Descriptor instead.
func (*CreateRoleRes) Descriptor() ([]byte, []int) {
	return file_backend_role_v1_role_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoleRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateRoleRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 更新角色请求
type UpdateRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" dc:"角色ID"`                       // 角色ID
	SiteId        int32                  `protobuf:"varint,2,opt,name=site_id,json=siteId,proto3" json:"site_id" dc:"站点ID"` // 站点ID
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name" dc:"角色名称"`                    // 角色名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleReq) Reset() {
	*x = UpdateRoleReq{}
	mi := &file_backend_role_v1_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleReq) ProtoMessage() {}

func (x *UpdateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_role_v1_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleReq.ProtoReflect.Descriptor instead.
func (*UpdateRoleReq) Descriptor() ([]byte, []int) {
	return file_backend_role_v1_role_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRoleReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoleReq) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *UpdateRoleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 更新角色响应
type UpdateRoleRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success" dc:"是否成功"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message" dc:"响应消息"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRes) Reset() {
	*x = UpdateRoleRes{}
	mi := &file_backend_role_v1_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRes) ProtoMessage() {}

func (x *UpdateRoleRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_role_v1_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRes.ProtoReflect.Descriptor instead.
func (*UpdateRoleRes) Descriptor() ([]byte, []int) {
	return file_backend_role_v1_role_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRoleRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateRoleRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 删除角色请求
type DeleteRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" dc:"角色ID"`                       // 角色ID
	SiteId        int32                  `protobuf:"varint,2,opt,name=site_id,json=siteId,proto3" json:"site_id" dc:"站点ID"` // 站点ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleReq) Reset() {
	*x = DeleteRoleReq{}
	mi := &file_backend_role_v1_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleReq) ProtoMessage() {}

func (x *DeleteRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_role_v1_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleReq.ProtoReflect.Descriptor instead.
func (*DeleteRoleReq) Descriptor() ([]byte, []int) {
	return file_backend_role_v1_role_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRoleReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteRoleReq) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

// 删除角色响应
type DeleteRoleRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success" dc:"是否成功"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message" dc:"响应消息"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRes) Reset() {
	*x = DeleteRoleRes{}
	mi := &file_backend_role_v1_role_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRes) ProtoMessage() {}

func (x *DeleteRoleRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_role_v1_role_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRes.ProtoReflect.Descriptor instead.
func (*DeleteRoleRes) Descriptor() ([]byte, []int) {
	return file_backend_role_v1_role_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRoleRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteRoleRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取权限列表请求
type GetPermissionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteId        int32                  `protobuf:"varint,1,opt,name=site_id,json=siteId,proto3" json:"site_id" dc:"站点ID"` // 站点ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionsReq) Reset() {
	*x = GetPermissionsReq{}
	mi := &file_backend_role_v1_role_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionsReq) ProtoMessage() {}

func (x *GetPermissionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_role_v1_role_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionsReq.ProtoReflect.Descriptor instead.
func (*GetPermissionsReq) Descriptor() ([]byte, []int) {
	return file_backend_role_v1_role_proto_rawDescGZIP(), []int{9}
}

func (x *GetPermissionsReq) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

// 权限信息
type PermissionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" dc:"权限ID"`                                      // 权限ID
	ParentId      int32                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id" dc:"父权限ID"`         // 父权限ID
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type" dc:"权限类型：1=菜单，2=操作权限"`                      // 权限类型：1=菜单，2=操作权限
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name" dc:"权限名称"`                                   // 权限名称
	BackendUrl    string                 `protobuf:"bytes,5,opt,name=backend_url,json=backendUrl,proto3" json:"backend_url" dc:"后台URL"`    // 后台URL
	FrontendUrl   string                 `protobuf:"bytes,6,opt,name=frontend_url,json=frontendUrl,proto3" json:"frontend_url" dc:"前台URL"` // 前台URL
	Open          bool                   `protobuf:"varint,7,opt,name=open,proto3" json:"open" dc:"是否展开"`                                  // 是否展开
	Checked       bool                   `protobuf:"varint,8,opt,name=checked,proto3" json:"checked" dc:"是否选中"`                            // 是否选中
	Children      []*PermissionInfo      `protobuf:"bytes,9,rep,name=children,proto3" json:"children" dc:"子权限列表"`                          // 子权限列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionInfo) Reset() {
	*x = PermissionInfo{}
	mi := &file_backend_role_v1_role_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionInfo) ProtoMessage() {}

func (x *PermissionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_role_v1_role_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionInfo.ProtoReflect.Descriptor instead.
func (*PermissionInfo) Descriptor() ([]byte, []int) {
	return file_backend_role_v1_role_proto_rawDescGZIP(), []int{10}
}

func (x *PermissionInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PermissionInfo) GetParentId() int32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *PermissionInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PermissionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermissionInfo) GetBackendUrl() string {
	if x != nil {
		return x.BackendUrl
	}
	return ""
}

func (x *PermissionInfo) GetFrontendUrl() string {
	if x != nil {
		return x.FrontendUrl
	}
	return ""
}

func (x *PermissionInfo) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

func (x *PermissionInfo) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

func (x *PermissionInfo) GetChildren() []*PermissionInfo {
	if x != nil {
		return x.Children
	}
	return nil
}

// 角色权限信息
type RolePermissionInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" dc:"角色ID"`                                                // 角色ID
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name" dc:"角色名称"`                                             // 角色名称
	PermissionList []string               `protobuf:"bytes,3,rep,name=permission_list,json=permissionList,proto3" json:"permission_list" dc:"权限ID列表"` // 权限ID列表
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RolePermissionInfo) Reset() {
	*x = RolePermissionInfo{}
	mi := &file_backend_role_v1_role_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermissionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionInfo) ProtoMessage() {}

func (x *RolePermissionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_role_v1_role_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionInfo.ProtoReflect.Descriptor instead.
func (*RolePermissionInfo) Descriptor() ([]byte, []int) {
	return file_backend_role_v1_role_proto_rawDescGZIP(), []int{11}
}

func (x *RolePermissionInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RolePermissionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RolePermissionInfo) GetPermissionList() []string {
	if x != nil {
		return x.PermissionList
	}
	return nil
}

// 获取权限列表响应
type GetPermissionsRes struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PermissionList []*PermissionInfo      `protobuf:"bytes,1,rep,name=permission_list,json=permissionList,proto3" json:"permission_list" dc:"权限树列表"` // 权限树列表
	RoleList       []*RolePermissionInfo  `protobuf:"bytes,2,rep,name=role_list,json=roleList,proto3" json:"role_list" dc:"角色权限列表"`                  // 角色权限列表
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPermissionsRes) Reset() {
	*x = GetPermissionsRes{}
	mi := &file_backend_role_v1_role_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionsRes) ProtoMessage() {}

func (x *GetPermissionsRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_role_v1_role_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionsRes.ProtoReflect.Descriptor instead.
func (*GetPermissionsRes) Descriptor() ([]byte, []int) {
	return file_backend_role_v1_role_proto_rawDescGZIP(), []int{12}
}

func (x *GetPermissionsRes) GetPermissionList() []*PermissionInfo {
	if x != nil {
		return x.PermissionList
	}
	return nil
}

func (x *GetPermissionsRes) GetRoleList() []*RolePermissionInfo {
	if x != nil {
		return x.RoleList
	}
	return nil
}

// 保存权限请求
type SavePermissionReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" dc:"角色ID"`                                                     // 角色ID
	SiteId         int32                  `protobuf:"varint,2,opt,name=site_id,json=siteId,proto3" json:"site_id" dc:"站点ID"`                               // 站点ID
	PermissionList string                 `protobuf:"bytes,3,opt,name=permission_list,json=permissionList,proto3" json:"permission_list" dc:"权限ID列表，逗号分隔"` // 权限ID列表，逗号分隔
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SavePermissionReq) Reset() {
	*x = SavePermissionReq{}
	mi := &file_backend_role_v1_role_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavePermissionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePermissionReq) ProtoMessage() {}

func (x *SavePermissionReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_role_v1_role_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePermissionReq.ProtoReflect.Descriptor instead.
func (*SavePermissionReq) Descriptor() ([]byte, []int) {
	return file_backend_role_v1_role_proto_rawDescGZIP(), []int{13}
}

func (x *SavePermissionReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SavePermissionReq) GetSiteId() int32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *SavePermissionReq) GetPermissionList() string {
	if x != nil {
		return x.PermissionList
	}
	return ""
}

// 保存权限响应
type SavePermissionRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success" dc:"是否成功"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message" dc:"响应消息"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavePermissionRes) Reset() {
	*x = SavePermissionRes{}
	mi := &file_backend_role_v1_role_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavePermissionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePermissionRes) ProtoMessage() {}

func (x *SavePermissionRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_role_v1_role_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePermissionRes.ProtoReflect.Descriptor instead.
func (*SavePermissionRes) Descriptor() ([]byte, []int) {
	return file_backend_role_v1_role_proto_rawDescGZIP(), []int{14}
}

func (x *SavePermissionRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SavePermissionRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_backend_role_v1_role_proto protoreflect.FileDescriptor

const file_backend_role_v1_role_proto_rawDesc = "" +
	"\n" +
	"\x1abackend/role/v1/role.proto\x12\x04role\")\n" +
	"\x0eGetRoleListReq\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\x05R\x06siteId\"\xbf\x01\n" +
	"\bRoleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\asite_id\x18\x02 \x01(\x05R\x06siteId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\x12 \n" +
	"\vpermissions\x18\a \x01(\tR\vpermissions\"6\n" +
	"\x0eGetRoleListRes\x12$\n" +
	"\x05roles\x18\x01 \x03(\v2\x0e.role.RoleInfoR\x05roles\"<\n" +
	"\rCreateRoleReq\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\x05R\x06siteId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"C\n" +
	"\rCreateRoleRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"L\n" +
	"\rUpdateRoleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\asite_id\x18\x02 \x01(\x05R\x06siteId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"C\n" +
	"\rUpdateRoleRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"8\n" +
	"\rDeleteRoleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\asite_id\x18\x02 \x01(\x05R\x06siteId\"C\n" +
	"\rDeleteRoleRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x11GetPermissionsReq\x12\x17\n" +
	"\asite_id\x18\x01 \x01(\x05R\x06siteId\"\x89\x02\n" +
	"\x0ePermissionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x05R\bparentId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1f\n" +
	"\vbackend_url\x18\x05 \x01(\tR\n" +
	"backendUrl\x12!\n" +
	"\ffrontend_url\x18\x06 \x01(\tR\vfrontendUrl\x12\x12\n" +
	"\x04open\x18\a \x01(\bR\x04open\x12\x18\n" +
	"\achecked\x18\b \x01(\bR\achecked\x120\n" +
	"\bchildren\x18\t \x03(\v2\x14.role.PermissionInfoR\bchildren\"a\n" +
	"\x12RolePermissionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0fpermission_list\x18\x03 \x03(\tR\x0epermissionList\"\x89\x01\n" +
	"\x11GetPermissionsRes\x12=\n" +
	"\x0fpermission_list\x18\x01 \x03(\v2\x14.role.PermissionInfoR\x0epermissionList\x125\n" +
	"\trole_list\x18\x02 \x03(\v2\x18.role.RolePermissionInfoR\broleList\"e\n" +
	"\x11SavePermissionReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\asite_id\x18\x02 \x01(\x05R\x06siteId\x12'\n" +
	"\x0fpermission_list\x18\x03 \x01(\tR\x0epermissionList\"G\n" +
	"\x11SavePermissionRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xfd\x02\n" +
	"\x04Role\x12;\n" +
	"\vGetRoleList\x12\x14.role.GetRoleListReq\x1a\x14.role.GetRoleListRes\"\x00\x128\n" +
	"\n" +
	"CreateRole\x12\x13.role.CreateRoleReq\x1a\x13.role.CreateRoleRes\"\x00\x128\n" +
	"\n" +
	"UpdateRole\x12\x13.role.UpdateRoleReq\x1a\x13.role.UpdateRoleRes\"\x00\x128\n" +
	"\n" +
	"DeleteRole\x12\x13.role.DeleteRoleReq\x1a\x13.role.DeleteRoleRes\"\x00\x12D\n" +
	"\x0eGetPermissions\x12\x17.role.GetPermissionsReq\x1a\x17.role.GetPermissionsRes\"\x00\x12D\n" +
	"\x0eSavePermission\x12\x17.role.SavePermissionReq\x1a\x17.role.SavePermissionRes\"\x00B&Z$jh_admin_service/api/backend/role/v1b\x06proto3"

var (
	file_backend_role_v1_role_proto_rawDescOnce sync.Once
	file_backend_role_v1_role_proto_rawDescData []byte
)

func file_backend_role_v1_role_proto_rawDescGZIP() []byte {
	file_backend_role_v1_role_proto_rawDescOnce.Do(func() {
		file_backend_role_v1_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_role_v1_role_proto_rawDesc), len(file_backend_role_v1_role_proto_rawDesc)))
	})
	return file_backend_role_v1_role_proto_rawDescData
}

var file_backend_role_v1_role_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_backend_role_v1_role_proto_goTypes = []any{
	(*GetRoleListReq)(nil),     // 0: role.GetRoleListReq
	(*RoleInfo)(nil),           // 1: role.RoleInfo
	(*GetRoleListRes)(nil),     // 2: role.GetRoleListRes
	(*CreateRoleReq)(nil),      // 3: role.CreateRoleReq
	(*CreateRoleRes)(nil),      // 4: role.CreateRoleRes
	(*UpdateRoleReq)(nil),      // 5: role.UpdateRoleReq
	(*UpdateRoleRes)(nil),      // 6: role.UpdateRoleRes
	(*DeleteRoleReq)(nil),      // 7: role.DeleteRoleReq
	(*DeleteRoleRes)(nil),      // 8: role.DeleteRoleRes
	(*GetPermissionsReq)(nil),  // 9: role.GetPermissionsReq
	(*PermissionInfo)(nil),     // 10: role.PermissionInfo
	(*RolePermissionInfo)(nil), // 11: role.RolePermissionInfo
	(*GetPermissionsRes)(nil),  // 12: role.GetPermissionsRes
	(*SavePermissionReq)(nil),  // 13: role.SavePermissionReq
	(*SavePermissionRes)(nil),  // 14: role.SavePermissionRes
}
var file_backend_role_v1_role_proto_depIdxs = []int32{
	1,  // 0: role.GetRoleListRes.roles:type_name -> role.RoleInfo
	10, // 1: role.PermissionInfo.children:type_name -> role.PermissionInfo
	10, // 2: role.GetPermissionsRes.permission_list:type_name -> role.PermissionInfo
	11, // 3: role.GetPermissionsRes.role_list:type_name -> role.RolePermissionInfo
	0,  // 4: role.Role.GetRoleList:input_type -> role.GetRoleListReq
	3,  // 5: role.Role.CreateRole:input_type -> role.CreateRoleReq
	5,  // 6: role.Role.UpdateRole:input_type -> role.UpdateRoleReq
	7,  // 7: role.Role.DeleteRole:input_type -> role.DeleteRoleReq
	9,  // 8: role.Role.GetPermissions:input_type -> role.GetPermissionsReq
	13, // 9: role.Role.SavePermission:input_type -> role.SavePermissionReq
	2,  // 10: role.Role.GetRoleList:output_type -> role.GetRoleListRes
	4,  // 11: role.Role.CreateRole:output_type -> role.CreateRoleRes
	6,  // 12: role.Role.UpdateRole:output_type -> role.UpdateRoleRes
	8,  // 13: role.Role.DeleteRole:output_type -> role.DeleteRoleRes
	12, // 14: role.Role.GetPermissions:output_type -> role.GetPermissionsRes
	14, // 15: role.Role.SavePermission:output_type -> role.SavePermissionRes
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_backend_role_v1_role_proto_init() }
func file_backend_role_v1_role_proto_init() {
	if File_backend_role_v1_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_role_v1_role_proto_rawDesc), len(file_backend_role_v1_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_role_v1_role_proto_goTypes,
		DependencyIndexes: file_backend_role_v1_role_proto_depIdxs,
		MessageInfos:      file_backend_role_v1_role_proto_msgTypes,
	}.Build()
	File_backend_role_v1_role_proto = out.File
	file_backend_role_v1_role_proto_goTypes = nil
	file_backend_role_v1_role_proto_depIdxs = nil
}
