// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "jh_admin_service/internal/logic/backend/admin"
	_ "jh_admin_service/internal/logic/backend/role"
	_ "jh_admin_service/internal/logic/backend/site"
	_ "jh_admin_service/internal/logic/backend/upload"
	_ "jh_admin_service/internal/logic/backend/user"
)
