// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: backend/upload/v1/upload.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadImageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileData      []byte                 `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data" dc:"文件二进制数据"`                            // 文件二进制数据
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name" dc:"原始文件名"`                              // 原始文件名
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type" dc:"文件MIME类型"`                  // 文件MIME类型
	FileSize      int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size" dc:"文件大小"`                              // 文件大小
	UploadCode    string                 `protobuf:"bytes,5,opt,name=upload_code,json=uploadCode,proto3" json:"upload_code" dc:"上传标识 (default, mobile_logo等)"` // 上传标识 (default, mobile_logo等)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageReq) Reset() {
	*x = UploadImageReq{}
	mi := &file_backend_upload_v1_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageReq) ProtoMessage() {}

func (x *UploadImageReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_upload_v1_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageReq.ProtoReflect.Descriptor instead.
func (*UploadImageReq) Descriptor() ([]byte, []int) {
	return file_backend_upload_v1_upload_proto_rawDescGZIP(), []int{0}
}

func (x *UploadImageReq) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *UploadImageReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadImageReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadImageReq) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadImageReq) GetUploadCode() string {
	if x != nil {
		return x.UploadCode
	}
	return ""
}

type UploadImageRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url" dc:"图片访问URL"` // 图片访问URL
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path" dc:"存储路径"`    // 存储路径
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size" dc:"文件大小"`   // 文件大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageRes) Reset() {
	*x = UploadImageRes{}
	mi := &file_backend_upload_v1_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRes) ProtoMessage() {}

func (x *UploadImageRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_upload_v1_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRes.ProtoReflect.Descriptor instead.
func (*UploadImageRes) Descriptor() ([]byte, []int) {
	return file_backend_upload_v1_upload_proto_rawDescGZIP(), []int{1}
}

func (x *UploadImageRes) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *UploadImageRes) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *UploadImageRes) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

var File_backend_upload_v1_upload_proto protoreflect.FileDescriptor

const file_backend_upload_v1_upload_proto_rawDesc = "" +
	"\n" +
	"\x1ebackend/upload/v1/upload.proto\x12\x06upload\"\xab\x01\n" +
	"\x0eUploadImageReq\x12\x1b\n" +
	"\tfile_data\x18\x01 \x01(\fR\bfileData\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\x12\x1f\n" +
	"\vupload_code\x18\x05 \x01(\tR\n" +
	"uploadCode\"g\n" +
	"\x0eUploadImageRes\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize2I\n" +
	"\x06Upload\x12?\n" +
	"\vUploadImage\x12\x16.upload.UploadImageReq\x1a\x16.upload.UploadImageRes\"\x00B(Z&jh_admin_service/api/backend/upload/v1b\x06proto3"

var (
	file_backend_upload_v1_upload_proto_rawDescOnce sync.Once
	file_backend_upload_v1_upload_proto_rawDescData []byte
)

func file_backend_upload_v1_upload_proto_rawDescGZIP() []byte {
	file_backend_upload_v1_upload_proto_rawDescOnce.Do(func() {
		file_backend_upload_v1_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_upload_v1_upload_proto_rawDesc), len(file_backend_upload_v1_upload_proto_rawDesc)))
	})
	return file_backend_upload_v1_upload_proto_rawDescData
}

var file_backend_upload_v1_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_backend_upload_v1_upload_proto_goTypes = []any{
	(*UploadImageReq)(nil), // 0: upload.UploadImageReq
	(*UploadImageRes)(nil), // 1: upload.UploadImageRes
}
var file_backend_upload_v1_upload_proto_depIdxs = []int32{
	0, // 0: upload.Upload.UploadImage:input_type -> upload.UploadImageReq
	1, // 1: upload.Upload.UploadImage:output_type -> upload.UploadImageRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_backend_upload_v1_upload_proto_init() }
func file_backend_upload_v1_upload_proto_init() {
	if File_backend_upload_v1_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_upload_v1_upload_proto_rawDesc), len(file_backend_upload_v1_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_upload_v1_upload_proto_goTypes,
		DependencyIndexes: file_backend_upload_v1_upload_proto_depIdxs,
		MessageInfos:      file_backend_upload_v1_upload_proto_msgTypes,
	}.Build()
	File_backend_upload_v1_upload_proto = out.File
	file_backend_upload_v1_upload_proto_goTypes = nil
	file_backend_upload_v1_upload_proto_depIdxs = nil
}
