// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SiteConfig is the golang structure of table site_config for DAO operations like Where/Data.
type SiteConfig struct {
	g.Meta               `orm:"table:site_config, do:true"`
	Id                   any         //
	SiteId               any         // 站点ID
	RegisterTimeInterval any         // 同一IP重复注册时间间隔
	SwitchRegister       any         // 是否开放注册
	SwitchGrade          any         // 会员等级开关
	DefaultGradeId       any         // 默认会员等级ID
	DefaultLevelId       any         // 默认会员层级ID
	DefaultAgentId       any         // 默认代理ID
	MobileLogo           any         // 手机端Logo
	MinWithdraw          any         // 单笔最低提现金额
	MaxWithdraw          any         // 单笔最高提现金额
	IsClose              any         // 是否关闭站点
	CloseReason          any         // 关闭原因
	UrlAgentPc           any         // 代理链接地址
	UrlMobile            any         // 手机域名地址
	UrlService           any         // 客服链接
	UrlAgentRegister     any         // 代理推广地址
	CreatedAt            *gtime.Time //
	UpdatedAt            *gtime.Time //
}
