// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SiteConfigDao is the data access object for table site_config.
type SiteConfigDao struct {
	table   string            // table is the underlying table name of the DAO.
	group   string            // group is the database configuration group name of current DAO.
	columns SiteConfigColumns // columns contains all the column names of Table for convenient usage.
}

// SiteConfigColumns defines and stores column names for table site_config.
type SiteConfigColumns struct {
	Id                   string //
	SiteId               string // 站点ID
	RegisterTimeInterval string // 同一IP重复注册时间间隔
	SwitchRegister       string // 是否开放注册
	SwitchGrade          string // 会员等级开关
	DefaultGradeId       string // 默认会员等级ID
	DefaultLevelId       string // 默认会员层级ID
	DefaultAgentId       string // 默认代理ID
	MobileLogo           string // 手机端Logo
	MinWithdraw          string // 单笔最低提现金额
	MaxWithdraw          string // 单笔最高提现金额
	IsClose              string // 是否关闭站点
	CloseReason          string // 关闭原因
	UrlAgentPc           string // 代理链接地址
	UrlMobile            string // 手机域名地址
	UrlService           string // 客服链接
	UrlAgentRegister     string // 代理推广地址
	CreatedAt            string //
	UpdatedAt            string //
}

// siteConfigColumns holds the columns for table site_config.
var siteConfigColumns = SiteConfigColumns{
	Id:                   "id",
	SiteId:               "site_id",
	RegisterTimeInterval: "register_time_interval",
	SwitchRegister:       "switch_register",
	SwitchGrade:          "switch_grade",
	DefaultGradeId:       "default_grade_id",
	DefaultLevelId:       "default_level_id",
	DefaultAgentId:       "default_agent_id",
	MobileLogo:           "mobile_logo",
	MinWithdraw:          "min_withdraw",
	MaxWithdraw:          "max_withdraw",
	IsClose:              "is_close",
	CloseReason:          "close_reason",
	UrlAgentPc:           "url_agent_pc",
	UrlMobile:            "url_mobile",
	UrlService:           "url_service",
	UrlAgentRegister:     "url_agent_register",
	CreatedAt:            "created_at",
	UpdatedAt:            "updated_at",
}

// NewSiteConfigDao creates and returns a new DAO object for table data access.
func NewSiteConfigDao() *SiteConfigDao {
	return &SiteConfigDao{
		group:   "default",
		table:   "site_config",
		columns: siteConfigColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SiteConfigDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SiteConfigDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SiteConfigDao) Columns() SiteConfigColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SiteConfigDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SiteConfigDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}
