// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pbentity/user.proto

package pbentity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`            // User ID
	Passport      string                 `protobuf:"bytes,2,opt,name=Passport,proto3" json:"Passport,omitempty"` // User Passport
	Password      string                 `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"` // User Password
	Nickname      string                 `protobuf:"bytes,4,opt,name=Nickname,proto3" json:"Nickname,omitempty"` // User Nickname
	CreateAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreateAt,proto3" json:"CreateAt,omitempty"` // Created Time
	UpdateAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=UpdateAt,proto3" json:"UpdateAt,omitempty"` // Updated Time
	DeleteAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=DeleteAt,proto3" json:"DeleteAt,omitempty"` // Deleted Time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_pbentity_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_pbentity_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetPassport() string {
	if x != nil {
		return x.Passport
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

func (x *User) GetUpdateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateAt
	}
	return nil
}

func (x *User) GetDeleteAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeleteAt
	}
	return nil
}

var File_pbentity_user_proto protoreflect.FileDescriptor

const file_pbentity_user_proto_rawDesc = "" +
	"\n" +
	"\x13pbentity/user.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\rR\x02Id\x12\x1a\n" +
	"\bPassport\x18\x02 \x01(\tR\bPassport\x12\x1a\n" +
	"\bPassword\x18\x03 \x01(\tR\bPassword\x12\x1a\n" +
	"\bNickname\x18\x04 \x01(\tR\bNickname\x126\n" +
	"\bCreateAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bCreateAt\x126\n" +
	"\bUpdateAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bUpdateAt\x126\n" +
	"\bDeleteAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bDeleteAtB\x1eZ\x1cjh_user_service/api/pbentityb\x06proto3"

var (
	file_pbentity_user_proto_rawDescOnce sync.Once
	file_pbentity_user_proto_rawDescData []byte
)

func file_pbentity_user_proto_rawDescGZIP() []byte {
	file_pbentity_user_proto_rawDescOnce.Do(func() {
		file_pbentity_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_user_proto_rawDesc), len(file_pbentity_user_proto_rawDesc)))
	})
	return file_pbentity_user_proto_rawDescData
}

var file_pbentity_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_user_proto_goTypes = []any{
	(*User)(nil),                  // 0: pbentity.User
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_user_proto_depIdxs = []int32{
	1, // 0: pbentity.User.CreateAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.User.UpdateAt:type_name -> google.protobuf.Timestamp
	1, // 2: pbentity.User.DeleteAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pbentity_user_proto_init() }
func file_pbentity_user_proto_init() {
	if File_pbentity_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_user_proto_rawDesc), len(file_pbentity_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_user_proto_goTypes,
		DependencyIndexes: file_pbentity_user_proto_depIdxs,
		MessageInfos:      file_pbentity_user_proto_msgTypes,
	}.Build()
	File_pbentity_user_proto = out.File
	file_pbentity_user_proto_goTypes = nil
	file_pbentity_user_proto_depIdxs = nil
}
