// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	v1 "jh_user_service/api/site/v1"
)

type (
	ISite interface {
		GetBasicSetting(ctx context.Context, req *v1.GetBasicSettingReq) (*v1.GetBasicSettingRes, error)
		UpdateBasicSetting(ctx context.Context, req *v1.UpdateBasicSettingReq) (*v1.UpdateBasicSettingRes, error)
	}
)

var (
	localSite ISite
)

func Site() ISite {
	if localSite == nil {
		panic("implement not found for interface ISite, forgot register?")
	}
	return localSite
}

func RegisterSite(i ISite) {
	localSite = i
}
