// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// activityTagDao is the data access object for the table activity_tag.
// You can define custom methods on it to extend its functionality as needed.
type activityTagDao struct {
	*internal.ActivityTagDao
}

var (
	// ActivityTag is a globally accessible object for table activity_tag operations.
	ActivityTag = activityTagDao{internal.NewActivityTagDao()}
)

// Add your custom methods and functionality below.
