// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// activityModuleDao is the data access object for the table activity_module.
// You can define custom methods on it to extend its functionality as needed.
type activityModuleDao struct {
	*internal.ActivityModuleDao
}

var (
	// ActivityModule is a globally accessible object for table activity_module operations.
	ActivityModule = activityModuleDao{internal.NewActivityModuleDao()}
)

// Add your custom methods and functionality below.
