// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// activityCustomDao is the data access object for the table activity_custom.
// You can define custom methods on it to extend its functionality as needed.
type activityCustomDao struct {
	*internal.ActivityCustomDao
}

var (
	// ActivityCustom is a globally accessible object for table activity_custom operations.
	ActivityCustom = activityCustomDao{internal.NewActivityCustomDao()}
)

// Add your custom methods and functionality below.
