// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// adDao is the data access object for the table ad.
// You can define custom methods on it to extend its functionality as needed.
type adDao struct {
	*internal.AdDao
}

var (
	// Ad is a globally accessible object for table ad operations.
	Ad = adDao{internal.NewAdDao()}
)

// Add your custom methods and functionality below.
