// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// adminCustomFieldDao is the data access object for the table admin_custom_field.
// You can define custom methods on it to extend its functionality as needed.
type adminCustomFieldDao struct {
	*internal.AdminCustomFieldDao
}

var (
	// AdminCustomField is a globally accessible object for table admin_custom_field operations.
	AdminCustomField = adminCustomFieldDao{internal.NewAdminCustomFieldDao()}
)

// Add your custom methods and functionality below.
