// =================================================================================
// This file is auto-generated by GoFrame CLI tool only once. Fill this file with your own code.
// =================================================================================

package dao

import (
	"jh_admin_service/internal/dao/internal"
)

// internalAdminPermissionDao is internal type for wrapping internal DAO implements.
type internalAdminPermissionDao = *internal.AdminPermissionDao

// adminPermissionDao is the data access object for table admin_permission.
// You can define custom methods on it to extend its functionality as you wish.
type adminPermissionDao struct {
	internalAdminPermissionDao
}

var (
	// AdminPermission is globally public accessible object for table admin_permission operations.
	AdminPermission = adminPermissionDao{
		internal.NewAdminPermissionDao(),
	}
)
