// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// adminLogDao is the data access object for the table admin_log.
// You can define custom methods on it to extend its functionality as needed.
type adminLogDao struct {
	*internal.AdminLogDao
}

var (
	// AdminLog is a globally accessible object for table admin_log operations.
	AdminLog = adminLogDao{internal.NewAdminLogDao()}
)

// Add your custom methods and functionality below.
