// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// agentMessageLogDao is the data access object for the table agent_message_log.
// You can define custom methods on it to extend its functionality as needed.
type agentMessageLogDao struct {
	*internal.AgentMessageLogDao
}

var (
	// AgentMessageLog is a globally accessible object for table agent_message_log operations.
	AgentMessageLog = agentMessageLogDao{internal.NewAgentMessageLogDao()}
)

// Add your custom methods and functionality below.
