// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// agentLogDao is the data access object for the table agent_log.
// You can define custom methods on it to extend its functionality as needed.
type agentLogDao struct {
	*internal.AgentLogDao
}

var (
	// AgentLog is a globally accessible object for table agent_log operations.
	AgentLog = agentLogDao{internal.NewAgentLogDao()}
)

// Add your custom methods and functionality below.
