// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// agentSharingLogDao is the data access object for the table agent_sharing_log.
// You can define custom methods on it to extend its functionality as needed.
type agentSharingLogDao struct {
	*internal.AgentSharingLogDao
}

var (
	// AgentSharingLog is a globally accessible object for table agent_sharing_log operations.
	AgentSharingLog = agentSharingLogDao{internal.NewAgentSharingLogDao()}
)

// Add your custom methods and functionality below.
