// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// agentDomainDao is the data access object for the table agent_domain.
// You can define custom methods on it to extend its functionality as needed.
type agentDomainDao struct {
	*internal.AgentDomainDao
}

var (
	// AgentDomain is a globally accessible object for table agent_domain operations.
	AgentDomain = agentDomainDao{internal.NewAgentDomainDao()}
)

// Add your custom methods and functionality below.
