// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// agentDao is the data access object for the table agent.
// You can define custom methods on it to extend its functionality as needed.
type agentDao struct {
	*internal.AgentDao
}

var (
	// Agent is a globally accessible object for table agent operations.
	Agent = agentDao{internal.NewAgentDao()}
)

// Add your custom methods and functionality below.
