// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// agentLevelDao is the data access object for the table agent_level.
// You can define custom methods on it to extend its functionality as needed.
type agentLevelDao struct {
	*internal.AgentLevelDao
}

var (
	// AgentLevel is a globally accessible object for table agent_level operations.
	AgentLevel = agentLevelDao{internal.NewAgentLevelDao()}
)

// Add your custom methods and functionality below.
