// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// betLogDailyDao is the data access object for the table bet_log_daily.
// You can define custom methods on it to extend its functionality as needed.
type betLogDailyDao struct {
	*internal.BetLogDailyDao
}

var (
	// BetLogDaily is a globally accessible object for table bet_log_daily operations.
	BetLogDaily = betLogDailyDao{internal.NewBetLogDailyDao()}
)

// Add your custom methods and functionality below.
