// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// customTagDao is the data access object for the table custom_tag.
// You can define custom methods on it to extend its functionality as needed.
type customTagDao struct {
	*internal.CustomTagDao
}

var (
	// CustomTag is a globally accessible object for table custom_tag operations.
	CustomTag = customTagDao{internal.NewCustomTagDao()}
)

// Add your custom methods and functionality below.
