// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// messageLogDao is the data access object for the table message_log.
// You can define custom methods on it to extend its functionality as needed.
type messageLogDao struct {
	*internal.MessageLogDao
}

var (
	// MessageLog is a globally accessible object for table message_log operations.
	MessageLog = messageLogDao{internal.NewMessageLogDao()}
)

// Add your custom methods and functionality below.
