// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// paymentAccountDao is the data access object for the table payment_account.
// You can define custom methods on it to extend its functionality as needed.
type paymentAccountDao struct {
	*internal.PaymentAccountDao
}

var (
	// PaymentAccount is a globally accessible object for table payment_account operations.
	PaymentAccount = paymentAccountDao{internal.NewPaymentAccountDao()}
)

// Add your custom methods and functionality below.
