// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// paymentAccountCopyDao is the data access object for the table payment_account_copy.
// You can define custom methods on it to extend its functionality as needed.
type paymentAccountCopyDao struct {
	*internal.PaymentAccountCopyDao
}

var (
	// PaymentAccountCopy is a globally accessible object for table payment_account_copy operations.
	PaymentAccountCopy = paymentAccountCopyDao{internal.NewPaymentAccountCopyDao()}
)

// Add your custom methods and functionality below.
