// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// rebateRuleOptionDao is the data access object for the table rebate_rule_option.
// You can define custom methods on it to extend its functionality as needed.
type rebateRuleOptionDao struct {
	*internal.RebateRuleOptionDao
}

var (
	// RebateRuleOption is a globally accessible object for table rebate_rule_option operations.
	RebateRuleOption = rebateRuleOptionDao{internal.NewRebateRuleOptionDao()}
)

// Add your custom methods and functionality below.
