// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// rebateRuleDao is the data access object for the table rebate_rule.
// You can define custom methods on it to extend its functionality as needed.
type rebateRuleDao struct {
	*internal.RebateRuleDao
}

var (
	// RebateRule is a globally accessible object for table rebate_rule operations.
	RebateRule = rebateRuleDao{internal.NewRebateRuleDao()}
)

// Add your custom methods and functionality below.
