// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// rebateRuleOptionGameDao is the data access object for the table rebate_rule_option_game.
// You can define custom methods on it to extend its functionality as needed.
type rebateRuleOptionGameDao struct {
	*internal.RebateRuleOptionGameDao
}

var (
	// RebateRuleOptionGame is a globally accessible object for table rebate_rule_option_game operations.
	RebateRuleOptionGame = rebateRuleOptionGameDao{internal.NewRebateRuleOptionGameDao()}
)

// Add your custom methods and functionality below.
