// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// rebateHistoryDao is the data access object for the table rebate_history.
// You can define custom methods on it to extend its functionality as needed.
type rebateHistoryDao struct {
	*internal.RebateHistoryDao
}

var (
	// RebateHistory is a globally accessible object for table rebate_history operations.
	RebateHistory = rebateHistoryDao{internal.NewRebateHistoryDao()}
)

// Add your custom methods and functionality below.
