// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// rechargeModuleDao is the data access object for the table recharge_module.
// You can define custom methods on it to extend its functionality as needed.
type rechargeModuleDao struct {
	*internal.RechargeModuleDao
}

var (
	// RechargeModule is a globally accessible object for table recharge_module operations.
	RechargeModule = rechargeModuleDao{internal.NewRechargeModuleDao()}
)

// Add your custom methods and functionality below.
