// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// riskForewarnConfigDao is the data access object for the table risk_forewarn_config.
// You can define custom methods on it to extend its functionality as needed.
type riskForewarnConfigDao struct {
	*internal.RiskForewarnConfigDao
}

var (
	// RiskForewarnConfig is a globally accessible object for table risk_forewarn_config operations.
	RiskForewarnConfig = riskForewarnConfigDao{internal.NewRiskForewarnConfigDao()}
)

// Add your custom methods and functionality below.
