// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// signLogDao is the data access object for the table sign_log.
// You can define custom methods on it to extend its functionality as needed.
type signLogDao struct {
	*internal.SignLogDao
}

var (
	// SignLog is a globally accessible object for table sign_log operations.
	SignLog = signLogDao{internal.NewSignLogDao()}
)

// Add your custom methods and functionality below.
