// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// siteGameDao is the data access object for the table site_game.
// You can define custom methods on it to extend its functionality as needed.
type siteGameDao struct {
	*internal.SiteGameDao
}

var (
	// SiteGame is a globally accessible object for table site_game operations.
	SiteGame = siteGameDao{internal.NewSiteGameDao()}
)

// Add your custom methods and functionality below.
