// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// siteSignDao is the data access object for the table site_sign.
// You can define custom methods on it to extend its functionality as needed.
type siteSignDao struct {
	*internal.SiteSignDao
}

var (
	// SiteSign is a globally accessible object for table site_sign operations.
	SiteSign = siteSignDao{internal.NewSiteSignDao()}
)

// Add your custom methods and functionality below.
