// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// siteRegisterDao is the data access object for the table site_register.
// You can define custom methods on it to extend its functionality as needed.
type siteRegisterDao struct {
	*internal.SiteRegisterDao
}

var (
	// SiteRegister is a globally accessible object for table site_register operations.
	SiteRegister = siteRegisterDao{internal.NewSiteRegisterDao()}
)

// Add your custom methods and functionality below.
