// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// internalSiteConfigDao is internal type for wrapping internal DAO implements.
type internalSiteConfigDao = *internal.SiteConfigDao

// siteConfigDao is the data access object for table site_config.
// You can define custom methods on it to extend its functionality as you wish.
type siteConfigDao struct {
	internalSiteConfigDao
}

var (
	// SiteConfig is globally public accessible object for table site_config operations.
	SiteConfig = siteConfigDao{
		internal.NewSiteConfigDao(),
	}
)

// Fill with you ideas below.
