// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// sitePointsDao is the data access object for the table site_points.
// You can define custom methods on it to extend its functionality as needed.
type sitePointsDao struct {
	*internal.SitePointsDao
}

var (
	// SitePoints is a globally accessible object for table site_points operations.
	SitePoints = sitePointsDao{internal.NewSitePointsDao()}
)

// Add your custom methods and functionality below.
