// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// siteDenyDao is the data access object for the table site_deny.
// You can define custom methods on it to extend its functionality as needed.
type siteDenyDao struct {
	*internal.SiteDenyDao
}

var (
	// SiteDeny is a globally accessible object for table site_deny operations.
	SiteDeny = siteDenyDao{internal.NewSiteDenyDao()}
)

// Add your custom methods and functionality below.
