// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// transferAccountDao is the data access object for the table transfer_account.
// You can define custom methods on it to extend its functionality as needed.
type transferAccountDao struct {
	*internal.TransferAccountDao
}

var (
	// TransferAccount is a globally accessible object for table transfer_account operations.
	TransferAccount = transferAccountDao{internal.NewTransferAccountDao()}
)

// Add your custom methods and functionality below.
