// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// userGradeDao is the data access object for the table user_grade.
// You can define custom methods on it to extend its functionality as needed.
type userGradeDao struct {
	*internal.UserGradeDao
}

var (
	// UserGrade is a globally accessible object for table user_grade operations.
	UserGrade = userGradeDao{internal.NewUserGradeDao()}
)

// Add your custom methods and functionality below.
