// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// userDailyReportDao is the data access object for the table user_daily_report.
// You can define custom methods on it to extend its functionality as needed.
type userDailyReportDao struct {
	*internal.UserDailyReportDao
}

var (
	// UserDailyReport is a globally accessible object for table user_daily_report operations.
	UserDailyReport = userDailyReportDao{internal.NewUserDailyReportDao()}
)

// Add your custom methods and functionality below.
