// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// userShippingAddressDao is the data access object for the table user_shipping_address.
// You can define custom methods on it to extend its functionality as needed.
type userShippingAddressDao struct {
	*internal.UserShippingAddressDao
}

var (
	// UserShippingAddress is a globally accessible object for table user_shipping_address operations.
	UserShippingAddress = userShippingAddressDao{internal.NewUserShippingAddressDao()}
)

// Add your custom methods and functionality below.
