// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// userLevelDao is the data access object for the table user_level.
// You can define custom methods on it to extend its functionality as needed.
type userLevelDao struct {
	*internal.UserLevelDao
}

var (
	// UserLevel is a globally accessible object for table user_level operations.
	UserLevel = userLevelDao{internal.NewUserLevelDao()}
)

// Add your custom methods and functionality below.
