// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// userLevelTransferDao is the data access object for the table user_level_transfer.
// You can define custom methods on it to extend its functionality as needed.
type userLevelTransferDao struct {
	*internal.UserLevelTransferDao
}

var (
	// UserLevelTransfer is a globally accessible object for table user_level_transfer operations.
	UserLevelTransfer = userLevelTransferDao{internal.NewUserLevelTransferDao()}
)

// Add your custom methods and functionality below.
