// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"jh_user_service/internal/dao/internal"
)

// userLevelPaymentDao is the data access object for the table user_level_payment.
// You can define custom methods on it to extend its functionality as needed.
type userLevelPaymentDao struct {
	*internal.UserLevelPaymentDao
}

var (
	// UserLevelPayment is a globally accessible object for table user_level_payment operations.
	UserLevelPayment = userLevelPaymentDao{internal.NewUserLevelPaymentDao()}
)

// Add your custom methods and functionality below.
