// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: backend/user/v1/user.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	User_GetUserList_FullMethodName      = "/user.User/GetUserList"
	User_UpdateUser_FullMethodName       = "/user.User/UpdateUser"
	User_GetUserBasicInfo_FullMethodName = "/user.User/GetUserBasicInfo"
	User_GetUserGrades_FullMethodName    = "/user.User/GetUserGrades"
	User_SaveUserGrades_FullMethodName   = "/user.User/SaveUserGrades"
	User_DeleteUserGrades_FullMethodName = "/user.User/DeleteUserGrades"
	User_GetUserLoginLogs_FullMethodName = "/user.User/GetUserLoginLogs"
)

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserClient interface {
	GetUserList(ctx context.Context, in *GetUserListReq, opts ...grpc.CallOption) (*GetUserListRes, error)
	UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserRes, error)
	GetUserBasicInfo(ctx context.Context, in *GetUserBasicInfoReq, opts ...grpc.CallOption) (*GetUserBasicInfoRes, error)
	// 用户等级相关接口
	GetUserGrades(ctx context.Context, in *GetUserGradesReq, opts ...grpc.CallOption) (*GetUserGradesRes, error)
	SaveUserGrades(ctx context.Context, in *SaveUserGradesReq, opts ...grpc.CallOption) (*SaveUserGradesRes, error)
	DeleteUserGrades(ctx context.Context, in *DeleteUserGradesReq, opts ...grpc.CallOption) (*DeleteUserGradesRes, error)
	// 用户登录日志接口
	GetUserLoginLogs(ctx context.Context, in *GetUserLoginLogsReq, opts ...grpc.CallOption) (*GetUserLoginLogsRes, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetUserList(ctx context.Context, in *GetUserListReq, opts ...grpc.CallOption) (*GetUserListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserListRes)
	err := c.cc.Invoke(ctx, User_GetUserList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserRes)
	err := c.cc.Invoke(ctx, User_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserBasicInfo(ctx context.Context, in *GetUserBasicInfoReq, opts ...grpc.CallOption) (*GetUserBasicInfoRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserBasicInfoRes)
	err := c.cc.Invoke(ctx, User_GetUserBasicInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserGrades(ctx context.Context, in *GetUserGradesReq, opts ...grpc.CallOption) (*GetUserGradesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserGradesRes)
	err := c.cc.Invoke(ctx, User_GetUserGrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) SaveUserGrades(ctx context.Context, in *SaveUserGradesReq, opts ...grpc.CallOption) (*SaveUserGradesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveUserGradesRes)
	err := c.cc.Invoke(ctx, User_SaveUserGrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) DeleteUserGrades(ctx context.Context, in *DeleteUserGradesReq, opts ...grpc.CallOption) (*DeleteUserGradesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserGradesRes)
	err := c.cc.Invoke(ctx, User_DeleteUserGrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserLoginLogs(ctx context.Context, in *GetUserLoginLogsReq, opts ...grpc.CallOption) (*GetUserLoginLogsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserLoginLogsRes)
	err := c.cc.Invoke(ctx, User_GetUserLoginLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility.
type UserServer interface {
	GetUserList(context.Context, *GetUserListReq) (*GetUserListRes, error)
	UpdateUser(context.Context, *UpdateUserReq) (*UpdateUserRes, error)
	GetUserBasicInfo(context.Context, *GetUserBasicInfoReq) (*GetUserBasicInfoRes, error)
	// 用户等级相关接口
	GetUserGrades(context.Context, *GetUserGradesReq) (*GetUserGradesRes, error)
	SaveUserGrades(context.Context, *SaveUserGradesReq) (*SaveUserGradesRes, error)
	DeleteUserGrades(context.Context, *DeleteUserGradesReq) (*DeleteUserGradesRes, error)
	// 用户登录日志接口
	GetUserLoginLogs(context.Context, *GetUserLoginLogsReq) (*GetUserLoginLogsRes, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServer struct{}

func (UnimplementedUserServer) GetUserList(context.Context, *GetUserListReq) (*GetUserListRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserList not implemented")
}
func (UnimplementedUserServer) UpdateUser(context.Context, *UpdateUserReq) (*UpdateUserRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedUserServer) GetUserBasicInfo(context.Context, *GetUserBasicInfoReq) (*GetUserBasicInfoRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserBasicInfo not implemented")
}
func (UnimplementedUserServer) GetUserGrades(context.Context, *GetUserGradesReq) (*GetUserGradesRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserGrades not implemented")
}
func (UnimplementedUserServer) SaveUserGrades(context.Context, *SaveUserGradesReq) (*SaveUserGradesRes, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveUserGrades not implemented")
}
func (UnimplementedUserServer) DeleteUserGrades(context.Context, *DeleteUserGradesReq) (*DeleteUserGradesRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUserGrades not implemented")
}
func (UnimplementedUserServer) GetUserLoginLogs(context.Context, *GetUserLoginLogsReq) (*GetUserLoginLogsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserLoginLogs not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}
func (UnimplementedUserServer) testEmbeddedByValue()              {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	// If the following call panics, it indicates UnimplementedUserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_GetUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserList(ctx, req.(*GetUserListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateUser(ctx, req.(*UpdateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserBasicInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserBasicInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserBasicInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserBasicInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserBasicInfo(ctx, req.(*GetUserBasicInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserGrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserGradesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserGrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserGrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserGrades(ctx, req.(*GetUserGradesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_SaveUserGrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveUserGradesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SaveUserGrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_SaveUserGrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SaveUserGrades(ctx, req.(*SaveUserGradesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_DeleteUserGrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserGradesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).DeleteUserGrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_DeleteUserGrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).DeleteUserGrades(ctx, req.(*DeleteUserGradesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserLoginLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserLoginLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserLoginLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserLoginLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserLoginLogs(ctx, req.(*GetUserLoginLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserList",
			Handler:    _User_GetUserList_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _User_UpdateUser_Handler,
		},
		{
			MethodName: "GetUserBasicInfo",
			Handler:    _User_GetUserBasicInfo_Handler,
		},
		{
			MethodName: "GetUserGrades",
			Handler:    _User_GetUserGrades_Handler,
		},
		{
			MethodName: "SaveUserGrades",
			Handler:    _User_SaveUserGrades_Handler,
		},
		{
			MethodName: "DeleteUserGrades",
			Handler:    _User_DeleteUserGrades_Handler,
		},
		{
			MethodName: "GetUserLoginLogs",
			Handler:    _User_GetUserLoginLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/user/v1/user.proto",
}
