// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: backend/user/v1/user.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取用户列表请求
type GetUserListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GradeId       int32                  `protobuf:"varint,1,opt,name=grade_id,json=gradeId,proto3" json:"grade_id" dc:"等级ID (可选)"`                   // 等级ID (可选)
	LevelId       int32                  `protobuf:"varint,2,opt,name=level_id,json=levelId,proto3" json:"level_id" dc:"层级ID (可选)"`                   // 层级ID (可选)
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status" dc:"状态 (可选)"`                                      // 状态 (可选)
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username" dc:"用户名 (可选)"`                                  // 用户名 (可选)
	Realname      string                 `protobuf:"bytes,5,opt,name=realname,proto3" json:"realname" dc:"真实姓名 (可选)"`                                 // 真实姓名 (可选)
	AgentUsername string                 `protobuf:"bytes,6,opt,name=agent_username,json=agentUsername,proto3" json:"agent_username" dc:"代理用户名 (可选)"` // 代理用户名 (可选)
	Mobile        string                 `protobuf:"bytes,7,opt,name=mobile,proto3" json:"mobile" dc:"手机号 (可选)"`                                      // 手机号 (可选)
	Page          int32                  `protobuf:"varint,8,opt,name=page,proto3" json:"page" dc:"页码"`                                               // 页码
	Size          int32                  `protobuf:"varint,9,opt,name=size,proto3" json:"size" dc:"每页数量"`                                             // 每页数量
	SortField     string                 `protobuf:"bytes,10,opt,name=sort_field,json=sortField,proto3" json:"sort_field" dc:"排序字段 (可选)"`             // 排序字段 (可选)
	SortRule      int32                  `protobuf:"varint,11,opt,name=sort_rule,json=sortRule,proto3" json:"sort_rule" dc:"排序规则 1=ASC, 0=DESC (可选)"` // 排序规则 1=ASC, 0=DESC (可选)
	CardNo        string                 `protobuf:"bytes,12,opt,name=card_no,json=cardNo,proto3" json:"card_no" dc:"银行卡号 (可选)"`                      // 银行卡号 (可选)
	Domain        string                 `protobuf:"bytes,13,opt,name=domain,proto3" json:"domain" dc:"注册域名 (可选)"`                                    // 注册域名 (可选)
	StartDate     string                 `protobuf:"bytes,14,opt,name=start_date,json=startDate,proto3" json:"start_date" dc:"开始日期 (可选)"`             // 开始日期 (可选)
	EndDate       string                 `protobuf:"bytes,15,opt,name=end_date,json=endDate,proto3" json:"end_date" dc:"结束日期 (可选)"`                   // 结束日期 (可选)
	Charge        int32                  `protobuf:"varint,16,opt,name=charge,proto3" json:"charge" dc:"是否首存 1=是, 0=否 (可选)"`                          // 是否首存 1=是, 0=否 (可选)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserListReq) Reset() {
	*x = GetUserListReq{}
	mi := &file_backend_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListReq) ProtoMessage() {}

func (x *GetUserListReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListReq.ProtoReflect.Descriptor instead.
func (*GetUserListReq) Descriptor() ([]byte, []int) {
	return file_backend_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserListReq) GetGradeId() int32 {
	if x != nil {
		return x.GradeId
	}
	return 0
}

func (x *GetUserListReq) GetLevelId() int32 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

func (x *GetUserListReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetUserListReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserListReq) GetRealname() string {
	if x != nil {
		return x.Realname
	}
	return ""
}

func (x *GetUserListReq) GetAgentUsername() string {
	if x != nil {
		return x.AgentUsername
	}
	return ""
}

func (x *GetUserListReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *GetUserListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserListReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetUserListReq) GetSortField() string {
	if x != nil {
		return x.SortField
	}
	return ""
}

func (x *GetUserListReq) GetSortRule() int32 {
	if x != nil {
		return x.SortRule
	}
	return 0
}

func (x *GetUserListReq) GetCardNo() string {
	if x != nil {
		return x.CardNo
	}
	return ""
}

func (x *GetUserListReq) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *GetUserListReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetUserListReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GetUserListReq) GetCharge() int32 {
	if x != nil {
		return x.Charge
	}
	return 0
}

// 用户信息
type UserInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" dc:"用户ID"`                                                         // 用户ID
	Username         string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username" dc:"用户名"`                                               // 用户名
	GradeId          int32                  `protobuf:"varint,3,opt,name=grade_id,json=gradeId,proto3" json:"grade_id" dc:"等级ID"`                                // 等级ID
	GradeName        string                 `protobuf:"bytes,4,opt,name=grade_name,json=gradeName,proto3" json:"grade_name" dc:"等级名称"`                           // 等级名称
	LevelId          int32                  `protobuf:"varint,5,opt,name=level_id,json=levelId,proto3" json:"level_id" dc:"层级ID"`                                // 层级ID
	LevelName        string                 `protobuf:"bytes,6,opt,name=level_name,json=levelName,proto3" json:"level_name" dc:"层级名称"`                           // 层级名称
	AgentId          int32                  `protobuf:"varint,7,opt,name=agent_id,json=agentId,proto3" json:"agent_id" dc:"代理ID"`                                // 代理ID
	AgentUsername    string                 `protobuf:"bytes,8,opt,name=agent_username,json=agentUsername,proto3" json:"agent_username" dc:"代理用户名"`              // 代理用户名
	Status           int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status" dc:"状态"`                                                   // 状态
	RegisterIp       string                 `protobuf:"bytes,10,opt,name=register_ip,json=registerIp,proto3" json:"register_ip" dc:"注册IP"`                       // 注册IP
	RegisterTime     string                 `protobuf:"bytes,11,opt,name=register_time,json=registerTime,proto3" json:"register_time" dc:"注册时间"`                 // 注册时间
	RegisterUrl      string                 `protobuf:"bytes,12,opt,name=register_url,json=registerUrl,proto3" json:"register_url" dc:"注册URL"`                   // 注册URL
	LastLoginIp      string                 `protobuf:"bytes,13,opt,name=last_login_ip,json=lastLoginIp,proto3" json:"last_login_ip" dc:"最后登录IP"`                // 最后登录IP
	LastLoginTime    string                 `protobuf:"bytes,14,opt,name=last_login_time,json=lastLoginTime,proto3" json:"last_login_time" dc:"最后登录时间"`          // 最后登录时间
	LastLoginAddress string                 `protobuf:"bytes,15,opt,name=last_login_address,json=lastLoginAddress,proto3" json:"last_login_address" dc:"最后登录地址"` // 最后登录地址
	Realname         string                 `protobuf:"bytes,16,opt,name=realname,proto3" json:"realname" dc:"真实姓名"`                                             // 真实姓名
	Mobile           string                 `protobuf:"bytes,17,opt,name=mobile,proto3" json:"mobile" dc:"手机号"`                                                  // 手机号
	Email            string                 `protobuf:"bytes,18,opt,name=email,proto3" json:"email" dc:"邮箱"`                                                     // 邮箱
	FocusLevel       int32                  `protobuf:"varint,19,opt,name=focus_level,json=focusLevel,proto3" json:"focus_level" dc:"关注级别"`                      // 关注级别
	BalanceStatus    int32                  `protobuf:"varint,20,opt,name=balance_status,json=balanceStatus,proto3" json:"balance_status" dc:"资金状态"`             // 资金状态
	Balance          string                 `protobuf:"bytes,21,opt,name=balance,proto3" json:"balance" dc:"余额"`                                                 // 余额
	BalanceFrozen    string                 `protobuf:"bytes,22,opt,name=balance_frozen,json=balanceFrozen,proto3" json:"balance_frozen" dc:"冻结余额"`              // 冻结余额
	Points           string                 `protobuf:"bytes,23,opt,name=points,proto3" json:"points" dc:"积分"`                                                   // 积分
	CardNo           string                 `protobuf:"bytes,24,opt,name=card_no,json=cardNo,proto3" json:"card_no" dc:"银行卡号"`                                   // 银行卡号
	IsOnline         int32                  `protobuf:"varint,25,opt,name=is_online,json=isOnline,proto3" json:"is_online" dc:"是否在线"`                            // 是否在线
	PayTimes         int32                  `protobuf:"varint,26,opt,name=pay_times,json=payTimes,proto3" json:"pay_times" dc:"存款次数"`                            // 存款次数
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_backend_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_backend_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetGradeId() int32 {
	if x != nil {
		return x.GradeId
	}
	return 0
}

func (x *UserInfo) GetGradeName() string {
	if x != nil {
		return x.GradeName
	}
	return ""
}

func (x *UserInfo) GetLevelId() int32 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

func (x *UserInfo) GetLevelName() string {
	if x != nil {
		return x.LevelName
	}
	return ""
}

func (x *UserInfo) GetAgentId() int32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *UserInfo) GetAgentUsername() string {
	if x != nil {
		return x.AgentUsername
	}
	return ""
}

func (x *UserInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserInfo) GetRegisterIp() string {
	if x != nil {
		return x.RegisterIp
	}
	return ""
}

func (x *UserInfo) GetRegisterTime() string {
	if x != nil {
		return x.RegisterTime
	}
	return ""
}

func (x *UserInfo) GetRegisterUrl() string {
	if x != nil {
		return x.RegisterUrl
	}
	return ""
}

func (x *UserInfo) GetLastLoginIp() string {
	if x != nil {
		return x.LastLoginIp
	}
	return ""
}

func (x *UserInfo) GetLastLoginTime() string {
	if x != nil {
		return x.LastLoginTime
	}
	return ""
}

func (x *UserInfo) GetLastLoginAddress() string {
	if x != nil {
		return x.LastLoginAddress
	}
	return ""
}

func (x *UserInfo) GetRealname() string {
	if x != nil {
		return x.Realname
	}
	return ""
}

func (x *UserInfo) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetFocusLevel() int32 {
	if x != nil {
		return x.FocusLevel
	}
	return 0
}

func (x *UserInfo) GetBalanceStatus() int32 {
	if x != nil {
		return x.BalanceStatus
	}
	return 0
}

func (x *UserInfo) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *UserInfo) GetBalanceFrozen() string {
	if x != nil {
		return x.BalanceFrozen
	}
	return ""
}

func (x *UserInfo) GetPoints() string {
	if x != nil {
		return x.Points
	}
	return ""
}

func (x *UserInfo) GetCardNo() string {
	if x != nil {
		return x.CardNo
	}
	return ""
}

func (x *UserInfo) GetIsOnline() int32 {
	if x != nil {
		return x.IsOnline
	}
	return 0
}

func (x *UserInfo) GetPayTimes() int32 {
	if x != nil {
		return x.PayTimes
	}
	return 0
}

// 获取用户列表响应
type GetUserListRes struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	List             []*UserInfo            `protobuf:"bytes,1,rep,name=list,proto3" json:"list" dc:"用户列表"`                                                      // 用户列表
	Count            int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count" dc:"总数量"`                                                    // 总数量
	TotalUsers       int32                  `protobuf:"varint,3,opt,name=total_users,json=totalUsers,proto3" json:"total_users" dc:"总用户数"`                       // 总用户数
	TotalChargeUsers int32                  `protobuf:"varint,4,opt,name=total_charge_users,json=totalChargeUsers,proto3" json:"total_charge_users" dc:"总充值用户数"` // 总充值用户数
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetUserListRes) Reset() {
	*x = GetUserListRes{}
	mi := &file_backend_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListRes) ProtoMessage() {}

func (x *GetUserListRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListRes.ProtoReflect.Descriptor instead.
func (*GetUserListRes) Descriptor() ([]byte, []int) {
	return file_backend_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserListRes) GetList() []*UserInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetUserListRes) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetUserListRes) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *GetUserListRes) GetTotalChargeUsers() int32 {
	if x != nil {
		return x.TotalChargeUsers
	}
	return 0
}

// 更新用户请求
type UpdateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" dc:"用户ID"`                                                // 用户ID
	LoginPassword string                 `protobuf:"bytes,2,opt,name=login_password,json=loginPassword,proto3" json:"login_password" dc:"登录密码 (可选)"` // 登录密码 (可选)
	PayPassword   string                 `protobuf:"bytes,3,opt,name=pay_password,json=payPassword,proto3" json:"pay_password" dc:"资金密码 (可选)"`       // 资金密码 (可选)
	GradeId       int32                  `protobuf:"varint,4,opt,name=grade_id,json=gradeId,proto3" json:"grade_id" dc:"等级ID"`                       // 等级ID
	LevelId       int32                  `protobuf:"varint,5,opt,name=level_id,json=levelId,proto3" json:"level_id" dc:"层级ID"`                       // 层级ID
	AgentId       int32                  `protobuf:"varint,6,opt,name=agent_id,json=agentId,proto3" json:"agent_id" dc:"代理ID"`                       // 代理ID
	Realname      string                 `protobuf:"bytes,7,opt,name=realname,proto3" json:"realname" dc:"真实姓名 (可选)"`                                // 真实姓名 (可选)
	Mobile        string                 `protobuf:"bytes,8,opt,name=mobile,proto3" json:"mobile" dc:"手机号 (可选)"`                                     // 手机号 (可选)
	Email         string                 `protobuf:"bytes,9,opt,name=email,proto3" json:"email" dc:"邮箱 (可选)"`                                        // 邮箱 (可选)
	Qq            string                 `protobuf:"bytes,10,opt,name=qq,proto3" json:"qq" dc:"QQ号 (可选)"`                                            // QQ号 (可选)
	Birthday      string                 `protobuf:"bytes,11,opt,name=birthday,proto3" json:"birthday" dc:"生日 (可选)"`                                 // 生日 (可选)
	Sex           int32                  `protobuf:"varint,12,opt,name=sex,proto3" json:"sex" dc:"性别"`                                               // 性别
	FocusLevel    int32                  `protobuf:"varint,13,opt,name=focus_level,json=focusLevel,proto3" json:"focus_level" dc:"关注级别"`             // 关注级别
	BalanceStatus int32                  `protobuf:"varint,14,opt,name=balance_status,json=balanceStatus,proto3" json:"balance_status" dc:"资金状态"`    // 资金状态
	Status        int32                  `protobuf:"varint,15,opt,name=status,proto3" json:"status" dc:"状态"`                                         // 状态
	Remark        string                 `protobuf:"bytes,16,opt,name=remark,proto3" json:"remark" dc:"备注 (可选)"`                                     // 备注 (可选)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserReq) Reset() {
	*x = UpdateUserReq{}
	mi := &file_backend_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserReq) ProtoMessage() {}

func (x *UpdateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserReq.ProtoReflect.Descriptor instead.
func (*UpdateUserReq) Descriptor() ([]byte, []int) {
	return file_backend_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserReq) GetLoginPassword() string {
	if x != nil {
		return x.LoginPassword
	}
	return ""
}

func (x *UpdateUserReq) GetPayPassword() string {
	if x != nil {
		return x.PayPassword
	}
	return ""
}

func (x *UpdateUserReq) GetGradeId() int32 {
	if x != nil {
		return x.GradeId
	}
	return 0
}

func (x *UpdateUserReq) GetLevelId() int32 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

func (x *UpdateUserReq) GetAgentId() int32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *UpdateUserReq) GetRealname() string {
	if x != nil {
		return x.Realname
	}
	return ""
}

func (x *UpdateUserReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UpdateUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserReq) GetQq() string {
	if x != nil {
		return x.Qq
	}
	return ""
}

func (x *UpdateUserReq) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *UpdateUserReq) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *UpdateUserReq) GetFocusLevel() int32 {
	if x != nil {
		return x.FocusLevel
	}
	return 0
}

func (x *UpdateUserReq) GetBalanceStatus() int32 {
	if x != nil {
		return x.BalanceStatus
	}
	return 0
}

func (x *UpdateUserReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateUserReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 更新用户响应
type UpdateUserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success" dc:"是否成功"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message" dc:"响应消息"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRes) Reset() {
	*x = UpdateUserRes{}
	mi := &file_backend_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRes) ProtoMessage() {}

func (x *UpdateUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRes.ProtoReflect.Descriptor instead.
func (*UpdateUserRes) Descriptor() ([]byte, []int) {
	return file_backend_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateUserRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取用户基本信息请求
type GetUserBasicInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" dc:"用户ID"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBasicInfoReq) Reset() {
	*x = GetUserBasicInfoReq{}
	mi := &file_backend_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBasicInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBasicInfoReq) ProtoMessage() {}

func (x *GetUserBasicInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBasicInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserBasicInfoReq) Descriptor() ([]byte, []int) {
	return file_backend_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserBasicInfoReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 用户基本信息
type UserBasicInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id" dc:"用户ID"`                                                         // 用户ID
	Username         string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username" dc:"用户名"`                                               // 用户名
	GradeName        string                 `protobuf:"bytes,3,opt,name=grade_name,json=gradeName,proto3" json:"grade_name" dc:"等级名称"`                           // 等级名称
	LevelName        string                 `protobuf:"bytes,4,opt,name=level_name,json=levelName,proto3" json:"level_name" dc:"层级名称"`                           // 层级名称
	Balance          string                 `protobuf:"bytes,5,opt,name=balance,proto3" json:"balance" dc:"余额"`                                                  // 余额
	RegisterTime     string                 `protobuf:"bytes,6,opt,name=register_time,json=registerTime,proto3" json:"register_time" dc:"注册时间"`                  // 注册时间
	RegisterIp       string                 `protobuf:"bytes,7,opt,name=register_ip,json=registerIp,proto3" json:"register_ip" dc:"注册IP"`                        // 注册IP
	LastLoginIp      string                 `protobuf:"bytes,8,opt,name=last_login_ip,json=lastLoginIp,proto3" json:"last_login_ip" dc:"最后登录IP"`                 // 最后登录IP
	LastLoginTime    string                 `protobuf:"bytes,9,opt,name=last_login_time,json=lastLoginTime,proto3" json:"last_login_time" dc:"最后登录时间"`           // 最后登录时间
	LastLoginAddress string                 `protobuf:"bytes,10,opt,name=last_login_address,json=lastLoginAddress,proto3" json:"last_login_address" dc:"最后登录地址"` // 最后登录地址
	AgentName        string                 `protobuf:"bytes,11,opt,name=agent_name,json=agentName,proto3" json:"agent_name" dc:"代理名称"`                          // 代理名称
	Realname         string                 `protobuf:"bytes,12,opt,name=realname,proto3" json:"realname" dc:"真实姓名"`                                             // 真实姓名
	Mobile           string                 `protobuf:"bytes,13,opt,name=mobile,proto3" json:"mobile" dc:"手机号"`                                                  // 手机号
	Email            string                 `protobuf:"bytes,14,opt,name=email,proto3" json:"email" dc:"邮箱"`                                                     // 邮箱
	Sex              int32                  `protobuf:"varint,15,opt,name=sex,proto3" json:"sex" dc:"性别"`                                                        // 性别
	Birthday         string                 `protobuf:"bytes,16,opt,name=birthday,proto3" json:"birthday" dc:"生日"`                                               // 生日
	Qq               string                 `protobuf:"bytes,17,opt,name=qq,proto3" json:"qq" dc:"QQ号"`                                                          // QQ号
	BalanceStatus    int32                  `protobuf:"varint,18,opt,name=balance_status,json=balanceStatus,proto3" json:"balance_status" dc:"资金状态"`             // 资金状态
	FocusLevel       int32                  `protobuf:"varint,19,opt,name=focus_level,json=focusLevel,proto3" json:"focus_level" dc:"关注级别"`                      // 关注级别
	Remark           string                 `protobuf:"bytes,20,opt,name=remark,proto3" json:"remark" dc:"备注"`                                                   // 备注
	Status           int32                  `protobuf:"varint,21,opt,name=status,proto3" json:"status" dc:"状态"`                                                  // 状态
	Device           string                 `protobuf:"bytes,22,opt,name=device,proto3" json:"device" dc:"最后登录设备"`                                               // 最后登录设备
	IsOnline         int32                  `protobuf:"varint,23,opt,name=is_online,json=isOnline,proto3" json:"is_online" dc:"是否在线"`                            // 是否在线
	Banks            []*BankInfo            `protobuf:"bytes,24,rep,name=banks,proto3" json:"banks" dc:"银行卡列表"`                                                  // 银行卡列表
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserBasicInfo) Reset() {
	*x = UserBasicInfo{}
	mi := &file_backend_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBasicInfo) ProtoMessage() {}

func (x *UserBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBasicInfo.ProtoReflect.Descriptor instead.
func (*UserBasicInfo) Descriptor() ([]byte, []int) {
	return file_backend_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserBasicInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserBasicInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserBasicInfo) GetGradeName() string {
	if x != nil {
		return x.GradeName
	}
	return ""
}

func (x *UserBasicInfo) GetLevelName() string {
	if x != nil {
		return x.LevelName
	}
	return ""
}

func (x *UserBasicInfo) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *UserBasicInfo) GetRegisterTime() string {
	if x != nil {
		return x.RegisterTime
	}
	return ""
}

func (x *UserBasicInfo) GetRegisterIp() string {
	if x != nil {
		return x.RegisterIp
	}
	return ""
}

func (x *UserBasicInfo) GetLastLoginIp() string {
	if x != nil {
		return x.LastLoginIp
	}
	return ""
}

func (x *UserBasicInfo) GetLastLoginTime() string {
	if x != nil {
		return x.LastLoginTime
	}
	return ""
}

func (x *UserBasicInfo) GetLastLoginAddress() string {
	if x != nil {
		return x.LastLoginAddress
	}
	return ""
}

func (x *UserBasicInfo) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *UserBasicInfo) GetRealname() string {
	if x != nil {
		return x.Realname
	}
	return ""
}

func (x *UserBasicInfo) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserBasicInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserBasicInfo) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *UserBasicInfo) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *UserBasicInfo) GetQq() string {
	if x != nil {
		return x.Qq
	}
	return ""
}

func (x *UserBasicInfo) GetBalanceStatus() int32 {
	if x != nil {
		return x.BalanceStatus
	}
	return 0
}

func (x *UserBasicInfo) GetFocusLevel() int32 {
	if x != nil {
		return x.FocusLevel
	}
	return 0
}

func (x *UserBasicInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *UserBasicInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserBasicInfo) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *UserBasicInfo) GetIsOnline() int32 {
	if x != nil {
		return x.IsOnline
	}
	return 0
}

func (x *UserBasicInfo) GetBanks() []*BankInfo {
	if x != nil {
		return x.Banks
	}
	return nil
}

// 银行卡信息
type BankInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BankName      string                 `protobuf:"bytes,1,opt,name=bank_name,json=bankName,proto3" json:"bank_name" dc:"银行名称"` // 银行名称
	CardNo        string                 `protobuf:"bytes,2,opt,name=card_no,json=cardNo,proto3" json:"card_no" dc:"银行卡号"`       // 银行卡号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankInfo) Reset() {
	*x = BankInfo{}
	mi := &file_backend_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankInfo) ProtoMessage() {}

func (x *BankInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankInfo.ProtoReflect.Descriptor instead.
func (*BankInfo) Descriptor() ([]byte, []int) {
	return file_backend_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *BankInfo) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *BankInfo) GetCardNo() string {
	if x != nil {
		return x.CardNo
	}
	return ""
}

// 获取用户基本信息响应
type GetUserBasicInfoRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserBasicInfo         `protobuf:"bytes,1,opt,name=user,proto3" json:"user" dc:"用户基本信息"` // 用户基本信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBasicInfoRes) Reset() {
	*x = GetUserBasicInfoRes{}
	mi := &file_backend_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBasicInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBasicInfoRes) ProtoMessage() {}

func (x *GetUserBasicInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_backend_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBasicInfoRes.ProtoReflect.Descriptor instead.
func (*GetUserBasicInfoRes) Descriptor() ([]byte, []int) {
	return file_backend_user_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserBasicInfoRes) GetUser() *UserBasicInfo {
	if x != nil {
		return x.User
	}
	return nil
}

var File_backend_user_v1_user_proto protoreflect.FileDescriptor

const file_backend_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x1abackend/user/v1/user.proto\x12\x04user\"\xbc\x03\n" +
	"\x0eGetUserListReq\x12\x19\n" +
	"\bgrade_id\x18\x01 \x01(\x05R\agradeId\x12\x19\n" +
	"\blevel_id\x18\x02 \x01(\x05R\alevelId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\brealname\x18\x05 \x01(\tR\brealname\x12%\n" +
	"\x0eagent_username\x18\x06 \x01(\tR\ragentUsername\x12\x16\n" +
	"\x06mobile\x18\a \x01(\tR\x06mobile\x12\x12\n" +
	"\x04page\x18\b \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\t \x01(\x05R\x04size\x12\x1d\n" +
	"\n" +
	"sort_field\x18\n" +
	" \x01(\tR\tsortField\x12\x1b\n" +
	"\tsort_rule\x18\v \x01(\x05R\bsortRule\x12\x17\n" +
	"\acard_no\x18\f \x01(\tR\x06cardNo\x12\x16\n" +
	"\x06domain\x18\r \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"start_date\x18\x0e \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x0f \x01(\tR\aendDate\x12\x16\n" +
	"\x06charge\x18\x10 \x01(\x05R\x06charge\"\xa5\x06\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x19\n" +
	"\bgrade_id\x18\x03 \x01(\x05R\agradeId\x12\x1d\n" +
	"\n" +
	"grade_name\x18\x04 \x01(\tR\tgradeName\x12\x19\n" +
	"\blevel_id\x18\x05 \x01(\x05R\alevelId\x12\x1d\n" +
	"\n" +
	"level_name\x18\x06 \x01(\tR\tlevelName\x12\x19\n" +
	"\bagent_id\x18\a \x01(\x05R\aagentId\x12%\n" +
	"\x0eagent_username\x18\b \x01(\tR\ragentUsername\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x1f\n" +
	"\vregister_ip\x18\n" +
	" \x01(\tR\n" +
	"registerIp\x12#\n" +
	"\rregister_time\x18\v \x01(\tR\fregisterTime\x12!\n" +
	"\fregister_url\x18\f \x01(\tR\vregisterUrl\x12\"\n" +
	"\rlast_login_ip\x18\r \x01(\tR\vlastLoginIp\x12&\n" +
	"\x0flast_login_time\x18\x0e \x01(\tR\rlastLoginTime\x12,\n" +
	"\x12last_login_address\x18\x0f \x01(\tR\x10lastLoginAddress\x12\x1a\n" +
	"\brealname\x18\x10 \x01(\tR\brealname\x12\x16\n" +
	"\x06mobile\x18\x11 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05email\x18\x12 \x01(\tR\x05email\x12\x1f\n" +
	"\vfocus_level\x18\x13 \x01(\x05R\n" +
	"focusLevel\x12%\n" +
	"\x0ebalance_status\x18\x14 \x01(\x05R\rbalanceStatus\x12\x18\n" +
	"\abalance\x18\x15 \x01(\tR\abalance\x12%\n" +
	"\x0ebalance_frozen\x18\x16 \x01(\tR\rbalanceFrozen\x12\x16\n" +
	"\x06points\x18\x17 \x01(\tR\x06points\x12\x17\n" +
	"\acard_no\x18\x18 \x01(\tR\x06cardNo\x12\x1b\n" +
	"\tis_online\x18\x19 \x01(\x05R\bisOnline\x12\x1b\n" +
	"\tpay_times\x18\x1a \x01(\x05R\bpayTimes\"\x99\x01\n" +
	"\x0eGetUserListRes\x12\"\n" +
	"\x04list\x18\x01 \x03(\v2\x0e.user.UserInfoR\x04list\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x1f\n" +
	"\vtotal_users\x18\x03 \x01(\x05R\n" +
	"totalUsers\x12,\n" +
	"\x12total_charge_users\x18\x04 \x01(\x05R\x10totalChargeUsers\"\xba\x03\n" +
	"\rUpdateUserReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12%\n" +
	"\x0elogin_password\x18\x02 \x01(\tR\rloginPassword\x12!\n" +
	"\fpay_password\x18\x03 \x01(\tR\vpayPassword\x12\x19\n" +
	"\bgrade_id\x18\x04 \x01(\x05R\agradeId\x12\x19\n" +
	"\blevel_id\x18\x05 \x01(\x05R\alevelId\x12\x19\n" +
	"\bagent_id\x18\x06 \x01(\x05R\aagentId\x12\x1a\n" +
	"\brealname\x18\a \x01(\tR\brealname\x12\x16\n" +
	"\x06mobile\x18\b \x01(\tR\x06mobile\x12\x14\n" +
	"\x05email\x18\t \x01(\tR\x05email\x12\x0e\n" +
	"\x02qq\x18\n" +
	" \x01(\tR\x02qq\x12\x1a\n" +
	"\bbirthday\x18\v \x01(\tR\bbirthday\x12\x10\n" +
	"\x03sex\x18\f \x01(\x05R\x03sex\x12\x1f\n" +
	"\vfocus_level\x18\r \x01(\x05R\n" +
	"focusLevel\x12%\n" +
	"\x0ebalance_status\x18\x0e \x01(\x05R\rbalanceStatus\x12\x16\n" +
	"\x06status\x18\x0f \x01(\x05R\x06status\x12\x16\n" +
	"\x06remark\x18\x10 \x01(\tR\x06remark\"C\n" +
	"\rUpdateUserRes\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"%\n" +
	"\x13GetUserBasicInfoReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xcd\x05\n" +
	"\rUserBasicInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"grade_name\x18\x03 \x01(\tR\tgradeName\x12\x1d\n" +
	"\n" +
	"level_name\x18\x04 \x01(\tR\tlevelName\x12\x18\n" +
	"\abalance\x18\x05 \x01(\tR\abalance\x12#\n" +
	"\rregister_time\x18\x06 \x01(\tR\fregisterTime\x12\x1f\n" +
	"\vregister_ip\x18\a \x01(\tR\n" +
	"registerIp\x12\"\n" +
	"\rlast_login_ip\x18\b \x01(\tR\vlastLoginIp\x12&\n" +
	"\x0flast_login_time\x18\t \x01(\tR\rlastLoginTime\x12,\n" +
	"\x12last_login_address\x18\n" +
	" \x01(\tR\x10lastLoginAddress\x12\x1d\n" +
	"\n" +
	"agent_name\x18\v \x01(\tR\tagentName\x12\x1a\n" +
	"\brealname\x18\f \x01(\tR\brealname\x12\x16\n" +
	"\x06mobile\x18\r \x01(\tR\x06mobile\x12\x14\n" +
	"\x05email\x18\x0e \x01(\tR\x05email\x12\x10\n" +
	"\x03sex\x18\x0f \x01(\x05R\x03sex\x12\x1a\n" +
	"\bbirthday\x18\x10 \x01(\tR\bbirthday\x12\x0e\n" +
	"\x02qq\x18\x11 \x01(\tR\x02qq\x12%\n" +
	"\x0ebalance_status\x18\x12 \x01(\x05R\rbalanceStatus\x12\x1f\n" +
	"\vfocus_level\x18\x13 \x01(\x05R\n" +
	"focusLevel\x12\x16\n" +
	"\x06remark\x18\x14 \x01(\tR\x06remark\x12\x16\n" +
	"\x06status\x18\x15 \x01(\x05R\x06status\x12\x16\n" +
	"\x06device\x18\x16 \x01(\tR\x06device\x12\x1b\n" +
	"\tis_online\x18\x17 \x01(\x05R\bisOnline\x12$\n" +
	"\x05banks\x18\x18 \x03(\v2\x0e.user.BankInfoR\x05banks\"@\n" +
	"\bBankInfo\x12\x1b\n" +
	"\tbank_name\x18\x01 \x01(\tR\bbankName\x12\x17\n" +
	"\acard_no\x18\x02 \x01(\tR\x06cardNo\">\n" +
	"\x13GetUserBasicInfoRes\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.user.UserBasicInfoR\x04user2\xc9\x01\n" +
	"\x04User\x12;\n" +
	"\vGetUserList\x12\x14.user.GetUserListReq\x1a\x14.user.GetUserListRes\"\x00\x128\n" +
	"\n" +
	"UpdateUser\x12\x13.user.UpdateUserReq\x1a\x13.user.UpdateUserRes\"\x00\x12J\n" +
	"\x10GetUserBasicInfo\x12\x19.user.GetUserBasicInfoReq\x1a\x19.user.GetUserBasicInfoRes\"\x00B&Z$jh_admin_service/api/backend/user/v1b\x06proto3"

var (
	file_backend_user_v1_user_proto_rawDescOnce sync.Once
	file_backend_user_v1_user_proto_rawDescData []byte
)

func file_backend_user_v1_user_proto_rawDescGZIP() []byte {
	file_backend_user_v1_user_proto_rawDescOnce.Do(func() {
		file_backend_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_user_v1_user_proto_rawDesc), len(file_backend_user_v1_user_proto_rawDesc)))
	})
	return file_backend_user_v1_user_proto_rawDescData
}

var file_backend_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_backend_user_v1_user_proto_goTypes = []any{
	(*GetUserListReq)(nil),      // 0: user.GetUserListReq
	(*UserInfo)(nil),            // 1: user.UserInfo
	(*GetUserListRes)(nil),      // 2: user.GetUserListRes
	(*UpdateUserReq)(nil),       // 3: user.UpdateUserReq
	(*UpdateUserRes)(nil),       // 4: user.UpdateUserRes
	(*GetUserBasicInfoReq)(nil), // 5: user.GetUserBasicInfoReq
	(*UserBasicInfo)(nil),       // 6: user.UserBasicInfo
	(*BankInfo)(nil),            // 7: user.BankInfo
	(*GetUserBasicInfoRes)(nil), // 8: user.GetUserBasicInfoRes
}
var file_backend_user_v1_user_proto_depIdxs = []int32{
	1, // 0: user.GetUserListRes.list:type_name -> user.UserInfo
	7, // 1: user.UserBasicInfo.banks:type_name -> user.BankInfo
	6, // 2: user.GetUserBasicInfoRes.user:type_name -> user.UserBasicInfo
	0, // 3: user.User.GetUserList:input_type -> user.GetUserListReq
	3, // 4: user.User.UpdateUser:input_type -> user.UpdateUserReq
	5, // 5: user.User.GetUserBasicInfo:input_type -> user.GetUserBasicInfoReq
	2, // 6: user.User.GetUserList:output_type -> user.GetUserListRes
	4, // 7: user.User.UpdateUser:output_type -> user.UpdateUserRes
	8, // 8: user.User.GetUserBasicInfo:output_type -> user.GetUserBasicInfoRes
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_backend_user_v1_user_proto_init() }
func file_backend_user_v1_user_proto_init() {
	if File_backend_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_user_v1_user_proto_rawDesc), len(file_backend_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_user_v1_user_proto_goTypes,
		DependencyIndexes: file_backend_user_v1_user_proto_depIdxs,
		MessageInfos:      file_backend_user_v1_user_proto_msgTypes,
	}.Build()
	File_backend_user_v1_user_proto = out.File
	file_backend_user_v1_user_proto_goTypes = nil
	file_backend_user_v1_user_proto_depIdxs = nil
}
