// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SiteConfig is the golang structure for table site_config.
type SiteConfig struct {
	Id                   uint        `json:"id"                     orm:"id"                       description:""`
	SiteId               int         `json:"siteId"                 orm:"site_id"                  description:"站点ID"`
	RegisterTimeInterval int         `json:"registerTimeInterval"   orm:"register_time_interval"   description:"同一IP重复注册时间间隔"`
	SwitchRegister       int         `json:"switchRegister"         orm:"switch_register"          description:"是否开放注册"`
	SwitchGrade          int         `json:"switchGrade"            orm:"switch_grade"             description:"会员等级开关"`
	DefaultGradeId       int         `json:"defaultGradeId"         orm:"default_grade_id"         description:"默认会员等级ID"`
	DefaultLevelId       int         `json:"defaultLevelId"         orm:"default_level_id"         description:"默认会员层级ID"`
	DefaultAgentId       int         `json:"defaultAgentId"         orm:"default_agent_id"         description:"默认代理ID"`
	MobileLogo           string      `json:"mobileLogo"             orm:"mobile_logo"              description:"手机端Logo"`
	MinWithdraw          float64     `json:"minWithdraw"            orm:"min_withdraw"             description:"单笔最低提现金额"`
	MaxWithdraw          float64     `json:"maxWithdraw"            orm:"max_withdraw"             description:"单笔最高提现金额"`
	IsClose              int         `json:"isClose"                orm:"is_close"                 description:"是否关闭站点"`
	CloseReason          string      `json:"closeReason"            orm:"close_reason"             description:"关闭原因"`
	UrlAgentPc           string      `json:"urlAgentPc"             orm:"url_agent_pc"             description:"代理链接地址"`
	UrlMobile            string      `json:"urlMobile"              orm:"url_mobile"               description:"手机域名地址"`
	UrlService           string      `json:"urlService"             orm:"url_service"              description:"客服链接"`
	UrlAgentRegister     string      `json:"urlAgentRegister"       orm:"url_agent_register"       description:"代理推广地址"`
	CreatedAt            *gtime.Time `json:"createdAt"              orm:"created_at"               description:""`
	UpdatedAt            *gtime.Time `json:"updatedAt"              orm:"updated_at"               description:""`
}
